### PR TITLE
fix exit code mismatch

### PR DESCRIPTION
**Pull request by noot**
**Summary of changes**
Changes introduced in this pull request:
- fix exit code mismatch causing receipt root mismatch on mainnet

**Reference issue to close (if applicable)**

Closes n/a

**Other information and links**

### CODE REVIEW

**Comment by lemmih** [comment]
Are there some situations where we need to return `SysErrForbidden` and others where `ErrForbidden` is correct?

**Comment by elmattic** [comment]
> Are there some situations where we need to return `SysErrForbidden` and others where `ErrForbidden` is correct?

The rule of thumb is that `SysErrXXX` errors must be used in non-actor code only (so here the VM) while `ErrXXX` are actor code only.

**Comment by lemmih** [comment]
I think we're using test-vectors that are no longer valid. Re-generating the test vectors from scratch changes the expected exit codes.

**Comment by lemmih** [comment]
Here's the patch that changed the test vector: https://github.com/filecoin-project/specs-actors/pull/1566

Note that they only updated the `specs-actors` repository and not the `test-vectors` repository.

**Comment by noot** [comment]
@lemmih since we directly pull `test-vectors` as a submodule we need to either wait for the repo to be updated with the correct vectors to get CI to pass, or to fix it ourselves (which as you pointed out is cumbersome).

**Comment by lemmih** [comment]
> @lemmih since we directly pull `test-vectors` as a submodule we need to either wait for the repo to be updated with the correct vectors to get CI to pass, or to fix it ourselves (which as you pointed out is cumbersome).

As a short-term solution, I say we fork `test-vectors` and update the vectors ourselves.

**Comment by lemmih** [comment]
Hi noot! I disabled the borked test vectors and pull in their replacement to the `extra-vectors/` folder. Not all of the updated test vectors pass but I think we can tackle that in another PR.

**Comment by noot** [comment]
@lemmih thanks! I can tackle the failing test in a follow up PR.

**Pull request merged**
