### PR TITLE
Try waiting for more blocks

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:

- Double the number of tries when checking send of FIL token

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@elmattic can you confirm this actually helps? In others words, did we have a situation where the funds arrived at 15th retry or so?

**Comment by elmattic** [comment]
> @elmattic can you confirm this actually helps? In others words, did we have a situation where the funds arrived at 15th retry or so?

Yes, many times.

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by elmattic** [comment]
@lemmih @LesnyRumcajs That said, in theory if a message is broadcasted to the network it should be mined at some point.

But each time the test was failing I tried to look for it on a block explorer and never found it.
So a real issue could hide behind this fiasco (maybe related to this issue https://github.com/ChainSafe/forest/issues/2761).

**Comment by LesnyRumcajs** [comment]
@elmattic like you commented here https://github.com/ChainSafe/forest/issues/2726#issuecomment-1488321748, a first step would be to print the message cid.

**Comment by elmattic** [comment]
> @elmattic like you commented here [#2726 (comment)](https://github.com/ChainSafe/forest/issues/2726#issuecomment-1488321748), a first step would be to print the message cid.

Thanks reminding me. Doing it in #2798.

**Pull request merged**
