### PR TITLE
chore: upgrade libp2p to 0.53

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

Changes introduced in this pull request:

- upgrade libp2p to 0.53

## Reference issue to close (if applicable)

Closes

## Other information and links

https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-v0.53.0

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@hanabi1224 did you run this on mainnet for a few days? Given our past experience with libp2p upgrades, I believe this is necessary.

**Comment by hanabi1224** [comment]
> @hanabi1224 did you run this on mainnet for a few days? Given our past experience with libp2p upgrades, I believe this is necessary.

@LesnyRumcajs That makes sense, converting it to draft before having it running on DO droplet for a few days

**Comment by LesnyRumcajs** [comment]
@hanabi1224 how is it? How are the syncing speeds? Any failures?

**Comment by hanabi1224** [comment]
> @hanabi1224 how is it? How are the syncing speeds? Any failures?

Everything looks good. Forest is able to sync with normal speed.

**Review by LesnyRumcajs — APPROVED** [review]
Thanks a lot for testing this.

**Review by aatifsyed — APPROVED** [review]

**Comment by hanabi1224** [comment]
@aatifsyed @LesnyRumcajs This PR needs a re-approval after resolving the merge conflict in `Cargo.lock`. Thanks!

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
