### PR TITLE
handle bearer token

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
## Summary of changes

Changes introduced in this pull request:

- align JWT usage with Lotus (and in general JSON Web Token specification) - header values shall include the `Bearer` prefix. This is necessary, e.g., for the `api compare` to support sending `write` tokens to Lotus, see [Go JSON-RPC authorization handling](https://github.com/filecoin-project/go-jsonrpc/blob/17a35772b24f59ceee25cc8d8177a2b255a659ac/auth/handler.go#L29-L33).
- Added some tests to untested code.

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by hanabi1224 — APPROVED** [review]

**Review by ruseinov — CHANGES_REQUESTED** [review]
Since we now require `Bearer` prefix too - we need to make sure `api compare` and other tools that are parsing tokens from env or arguments prepend `Bearer` too, when the token is available.

**Comment by ruseinov** [comment]
Here's an example of `api compare` usage with specified token.

```forest-tool api compare "/Users/romanuseinov/Library/Application Support/com.ChainSafe.Forest/calibnet/0.17.2/car_db/1713525012514.forest.car.zst" --filter=SyncSub --forest "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXSwiZXhwIjoxNzE4NzE1NDA1fQ.iYPmOk-dytEbtdH7EmEE1tad83rvUqUgGkwKlD7VaO4:/ip4/127.0.0.1/tcp/2345/http"```

This will fail miserably, because `Bearer` prefix is required.

**Comment by LesnyRumcajs** [comment]
> Here's an example of `api compare` usage with specified token.
> 
> `forest-tool api compare "/Users/romanuseinov/Library/Application Support/com.ChainSafe.Forest/calibnet/0.17.2/car_db/1713525012514.forest.car.zst" --filter=SyncSub --forest "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXSwiZXhwIjoxNzE4NzE1NDA1fQ.iYPmOk-dytEbtdH7EmEE1tad83rvUqUgGkwKlD7VaO4:/ip4/127.0.0.1/tcp/2345/http"`
> 
> This will fail miserably, because `Bearer` prefix is required.

And the `Bearer` prefix is added in `client.rs`, thus satisfying the requirement.

**Comment by ruseinov** [comment]
> > Here's an example of `api compare` usage with specified token.
> > `forest-tool api compare "/Users/romanuseinov/Library/Application Support/com.ChainSafe.Forest/calibnet/0.17.2/car_db/1713525012514.forest.car.zst" --filter=SyncSub --forest "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXSwiZXhwIjoxNzE4NzE1NDA1fQ.iYPmOk-dytEbtdH7EmEE1tad83rvUqUgGkwKlD7VaO4:/ip4/127.0.0.1/tcp/2345/http"`
> > This will fail miserably, because `Bearer` prefix is required.
> 
> And the `Bearer` prefix is added in `client.rs`, thus satisfying the requirement.

My bad, I somehow managed to miss this change.

**Review by ruseinov — APPROVED** [review]

**Pull request merged**
