### PR TITLE
fix(rpc test): StateCall and StateReplay

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

For a detailed explanation, see https://github.com/ChainSafe/forest/issues/4432#issuecomment-2180557858

Changes introduced in this pull request:

- fix RPC test for StateCall and StateReplay by ignoring the `ReturnTrace::exit_code` field

Manually tested with the same snapshot that causes CI failures in https://github.com/ChainSafe/forest/actions/runs/9593268587/job/26453560366#step:5:39

```
forest-tool api compare /data/forest_snapshot_calibnet_2024-06-20_height_1718049.forest.car.zst --forest *** --lotus *** --n-tipsets 10 --filter-file /data/filter-list --miner-address t0111551 --worker-address t3sw466j35hqjbch5x7tcr7ona6idsgzypoturfci2ajqsfrrwhp7ty3ythtd7x646adaidnvxpdr5b2ftcciq
```

```
     Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-20_height_1718049.forest.car.zst --filter StateReplay`
| RPC Method                | Forest | Lotus |
|---------------------------|--------|-------|
| Filecoin.StateReplay (48) | Valid  | Valid |
```

```
     Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-20_height_1718049.forest.car.zst --filter StateCall`
| RPC Method              | Forest | Lotus |
|-------------------------|--------|-------|
| Filecoin.StateCall (48) | Valid  | Valid |
```

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by aatifsyed — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
I recommend we don't merge this so that it's clearly visible that the Forest and Lotus output differs at the currently used versions.

**Comment by LesnyRumcajs** [comment]
@hanabi1224 what do we do with this draft?

**Comment by LesnyRumcajs** [comment]
> @hanabi1224 what do we do with this draft?

bump

**Comment by hanabi1224** [comment]
Closing for now.

**Pull request closed without merging**
