### PR TITLE
fix(rpc): update StateSectorPreCommitInfo against v1 spec

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

(Part of #4424)
This PR fixes `StateSectorPreCommitInfo` RPC method against the v1 spec and uses it for both v0 and v1 endpoints until #3960 is resolved. (Keeping the v0 implementation with a different name for now)

Changes introduced in this pull request:

- update `StateSectorPreCommitInfo` against v1 spec

```
     Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-24_height_1729537.forest.car.zst --filter StateSectorPreCommitInfo`
| RPC Method                             | Forest
                       | Lotus                                                                                    |
|----------------------------------------|-----------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------|
| Filecoin.StateSectorPreCommitInfo (10) | Rejected("Unknown miner actor code bafk2bzacedjnrb5glewazsxpcx6rwiuhl4kwrfcqolyprn6rrjtlzmthlhdq6") | Rejected("(get sset) failed to load miner actor state: actor code is not miner: system") |
| Filecoin.StateSectorPreCommitInfo (37) | Valid
                       | Valid                                                                                    |
```

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
Are those `rejected` entries intended? If not, why do they happen?

**Comment by hanabi1224** [comment]
> Are those `rejected` entries intended? If not, why do they happen?

@LesnyRumcajs They are expected. There are test cases to cover invalid miner addresses

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
How about a changelog entry?

**Comment by hanabi1224** [comment]
> How about a changelog entry?

@LesnyRumcajs I'd prefer not to bloat the changelog(and create potential merge conflicts with others) with an entry for each individual RPC method. Maybe it would be better to use a milestone entry instead. Note that we still have the detailed autogenerated changelog for each PR on the release page. What do you think?

Echoing lemmih 's https://github.com/ChainSafe/forest/pull/4039#issuecomment-1983686248

> I'm okay with not having a changelog entry for each RPC method. Instead, we'll have an entry for each RPC milestone (full v0, full v1, full lotus compliance, etc).

**Review by lemmih — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
> > How about a changelog entry?
> 
> @LesnyRumcajs I'd prefer not to bloat the changelog(and create potential merge conflicts with others) with an entry for each individual RPC method. Maybe it would be better to use a milestone entry instead. Note that we still have the detailed autogenerated changelog for each PR on the release page. What do you think?
> 
> Echoing lemmih 's [#4039 (comment)](https://github.com/ChainSafe/forest/pull/4039#issuecomment-1983686248)
> 
> > I'm okay with not having a changelog entry for each RPC method. Instead, we'll have an entry for each RPC milestone (full v0, full v1, full lotus compliance, etc).

I don't necessarily agree, and at this point it's simply inconsistent. The current changelog for the new release already has several entries with RPC methods and their fixes. https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md#breaking

While I'm not going to fight for having all RPC methods listed in the changelog (though it's my preference and it makes listing the changes and summarizing them easier), I'd very much suggest having a consistent changelog.

**Comment by hanabi1224** [comment]
@LesnyRumcajs changelog updated

**Review by ruseinov — APPROVED** [review]

**Comment by ruseinov** [comment]
> While I'm not going to fight for having all RPC methods listed in the changelog (though it's my preference and it makes listing the changes and summarizing them easier), I'd very much suggest having a consistent changelog.

Totally onboard with this, if we didn't want the RPC methods listed in `CHANGELOG.md` - we should have listed them before. It's a bit too late now to change this strategy.

**Pull request merged**
