### PR TITLE
Fix Sync Wait to wait until forest enters follow mode

### LINKED ISSUE #3540: `forest-cli sync wait` exits too early
**Issue summary**

The `forest-cli sync wait` RPC call doesn't wait until Forest has entered the `follow` mode. Instead, it merely waits for the completion of a single `sync-range` step. When syncing to a network, Forest will query the current HEAD and then initiate a `sync-range` from the heaviest tipset to the current HEAD. This step is then repeated until Forest has caught up. When we call `forest-cli sync wait`, we should wait until Forest has completely caught up rather than waiting for a single `sync-range` step.

Acceptance criteria:
- [ ] `forest-cli sync wait` guarantees that Forest is in the `follow` mode.

**Other information and links**

### PR DESCRIPTION
**Pull request by sudo-shashank**
## Summary of changes

Changes introduced in this pull request:

- Fixed `Sync Wait` command to wait until forest enters follow mode

## Reference issue to close (if applicable)

Closes #3540 

## Change checklist

- [X] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation,
- [X] I have added tests that prove my fix is effective or that my feature works (if possible),
- [X] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by lemmih** [comment]
`SyncStage` has to match the structure of the same name in Lotus. The stage should not be set to `Complete` before we're in `follow` mode.

**Review by lemmih — CHANGES_REQUESTED** [review]
`SyncStage` should ideally not deviate from Lotus.

**Review by lemmih — APPROVED** [review]

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by lemmih** [comment]
@sudo-shashank Oh, could you add a changelog entry? This fixes a user-visible bug.

**Comment by sudo-shashank** [comment]
> @sudo-shashank Oh, could you add a changelog entry? This fixes a user-visible bug.

added

**Review by lemmih — APPROVED** [review]

**Review by lemmih — APPROVED** [review]

**Pull request merged**
