### PR TITLE
Reference files with PathBuf instead of Strings

### LINKED ISSUE #1158: Refactor String formatting used to reference Files using Path builders
**Task summary**

Runtime String formatting is used instead of Path builders to construct paths. This is likely less optimal and idiomatic to Rust, and should be refactored throughout the entire codebase.

**Specification reference**

- [ ] Find and replace all instances of format when used to refer to files in our code to instead use a Path builder.

**Other information and links**

https://github.com/ChainSafe/forest/pull/1151#issuecomment-858843686

### PR DESCRIPTION
**Pull request by leviathanbeak**
**Summary of changes**
Changes introduced in this pull request:
- switched to PathBuf instead of &str at places where Files and Folders are referenced
- refactored few places for more idiomatic use of PathBufs

**Reference issue to close (if applicable)**
Closes #1158

### CODE REVIEW

**Review by cryptoquick — APPROVED** [review]
Looks good, thank you!

**Review by cryptoquick — CHANGES_REQUESTED** [review]
Oh, one thing. Looks like this broke the linter. It made some good points. Can you take a look at the following issues?
https://app.circleci.com/pipelines/github/ChainSafe/forest/4930/workflows/c2328c6f-b6ed-43bf-afca-65ffd218ed4d/jobs/20505/parallel-runs/0/steps/0-111

**Comment by leviathanbeak** [comment]
@cryptoquick thanks for the review, and than you clippy for suggestions, updated it

**Review by cryptoquick — APPROVED** [review]
Great! I'm good with cleanup as long as Clippy abides. I've found its insights really helpful.

**Review by connormullett — APPROVED** [review]
LGTM! Thanks for the contribution

**Comment by cryptoquick** [comment]
@leviathanbeak Thanks again for your contributions. Merged!

**Pull request merged**
