### PR TITLE
Fix `ApiHeadChange` type

### LINKED ISSUE #4371: `ChainNotify` erroneous behavior
## Describe the bug

There appears to be two bugs here:
1. `ChainNotify` yields one extra `Apply` change, same as `Current`
2. This only seems to happen for the first registered listener; the same change reported as `Current` is repeated once as Apply for the first registered listener, so multiple `ChainNotify` listeners get different results across for each change

See log for more details. The two lines per log entry are two `ChainNotify` WS readers 

## To reproduce

1. Run Lotus and Forest and connect them
4. Run one or more miners on Lotus
5. Attach two or more listeners via `ChainNotify` WS

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
2024-05-28T09:36:25.865487Z  WARN lotus: Head change: current, Height: 838, CIDs bafy2bzacecc2u5qroitwqdavyj5rl6hejpnd5wqy5qhdrh57ct662uddrwtmw
2024-05-28T09:36:25.900517Z  WARN lotus: Head change: current, Height: 838, CIDs: bafy2bzacecc2u5qroitwqdavyj5rl6hejpnd5wqy5qhdrh57ct662uddrwtmw

2024-05-28T09:36:26.064284Z  WARN lotus: Head change: apply, Height: 839, CIDs: bafy2bzacedvrpxjktwd66ddhgvwuw35r7lrquihwwt4sjdrzy3y4j3wp2qso6
2024-05-28T09:36:26.065248Z  WARN lotus: Head change: apply, Height: 839, CIDs: bafy2bzacedvrpxjktwd66ddhgvwuw35r7lrquihwwt4sjdrzy3y4j3wp2qso6

2024-05-28T09:36:30.063523Z  WARN lotus: Head change: apply, Height: 840, CIDs: bafy2bzacea5hipinm2atf6payqyf4fljlemzq6srbcx3llt6lfubjzljvccfy
2024-05-28T09:36:30.064311Z  WARN lotus: Head change: apply, Height: 840, CIDs: bafy2bzacea5hipinm2atf6payqyf4fljlemzq6srbcx3llt6lfubjzljvccfy

...

2024-05-28T09:37:37.193983Z  WARN forest: Head change: current, Height: 856, CIDs: bafy2bzaceb5nsmc44vig5rny7gk7rxf5jwmmeacgn5lyqmeo77u37d3rzuycg
2024-05-28T09:37:37.194269Z  WARN forest: Head change: current, Height: 856, CIDs: bafy2bzaceb5nsmc44vig5rny7gk7rxf5jwmmeacgn5lyqmeo77u37d3rzuycg

2024-05-28T09:37:38.063049Z  WARN forest: Head change: apply, Height: 856, CIDs: bafy2bzaceb5nsmc44vig5rny7gk7rxf5jwmmeacgn5lyqmeo77u37d3rzuycg
2024-05-28T09:37:38.066762Z  WARN forest: Head change: apply, Height: 857, CIDs: bafy2bzaceaumuzo53m6vfojb4mdr7vsvwmco3ie3gvnurbbi6tjik2sfz2ly6

2024-05-28T09:37:42.074711Z  WARN forest: Head change: apply, Height: 857, CIDs: bafy2bzaceaumuzo53m6vfojb4mdr7vsvwmco3ie3gvnurbbi6tjik2sfz2ly6
2024-05-28T09:37:42.077869Z  WARN forest: Head change: apply, Height: 858, CIDs: bafy2bzacedmyovv23sn7nra5jwmltm5p5ot7pnkplnav7sat3ppb3tbzzhafw

2024-05-28T09:37:46.058826Z  WARN forest: Head change: apply, Height: 858, CIDs: bafy2bzacedmyovv23sn7nra5jwmltm5p5ot7pnkplnav7sat3ppb3tbzzhafw
2024-05-28T09:37:46.061476Z  WARN forest: Head change: apply, Height: 859, CIDs: bafy2bzacedw7ox4hxmuk7b6bitzk3toq7uoorj2aa45spwulhtenmffwtli6y


  ```
</details>

## Environment (please complete the following information):

- OS: Arch Linux via WSL2 :) (`5.15.90.1-microsoft-standard-WSL2`)
- Branch/commit https://github.com/ChainSafe/forest/pull/4357 merged `main` (`ca2d6a1b3d4d893273a93f176742a829d968bc67`)
- Hardware

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:

- Fix `ApiHeadChange` type

## Reference issue to close (if applicable)

Closes #4371, #4002

## Other information and links

The endpoint code is only being manually tested at the moment. I've attached the script used and what the result files look like once you have run it (using `node index.js`).
[index.txt](https://github.com/ChainSafe/forest/files/15407105/index.txt)
[forest.log](https://github.com/ChainSafe/forest/files/15407108/forest.log)
[lotus.log](https://github.com/ChainSafe/forest/files/15407111/lotus.log)

In the attached log files, we should have an exact match for notifications of the type `"current"`. We should have a match for notifications of type `"apply"` when `Val.Cids` values are the same.

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@alt-ivan could you please confirm that this change works for you?

**Comment by alt-ivan** [comment]
@LesnyRumcajs 
Sorry, I haven't been able to test yet due to other obligations. I will test on Monday and report back here.

**Comment by alt-ivan** [comment]
@LesnyRumcajs 
I have finally got around to testing this and the type changed introduced in this PR works.
However I found some other `ChainNotify` issues, opened an issue here: https://github.com/ChainSafe/forest/issues/4371

**Comment by elmattic** [comment]
@alt-ivan Many thanks for reporting this issue. I've committed a patch in this PR that should fix #4371.

Let me know if everything works well for you.

**Comment by elmattic** [comment]
@alt-ivan  I've committed a fix to properly support several WS clients. Can you have a second look? I've tested the following scenario on my side (on both macOS and Ubuntu):
- Two WS clients connect to the Forest node, where the second client creates two channels.

All three channel outputs look alike.

**Comment by alt-ivan** [comment]
@elmattic 

Awesome, thanks! I'll report back here as soon as I re-test everything

**Comment by alt-ivan** [comment]
@elmattic  

Hi, I have re-tested and can confirm that everything works as expected. I apologize for the delay!

**Comment by elmattic** [comment]
> Hi, I have re-tested and can confirm that everything works as expected. I apologize for the delay!

No worries! Thanks for your help with the testing.

**Review by hanabi1224 — APPROVED** [review]

**Review by lemmih — APPROVED** [review]

**Review by ruseinov — APPROVED** [review]

**Pull request merged**
