### PR TITLE
database migration plan

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
## Summary of changes

Changes introduced in this pull request:

- added a proposed database migration plan. I'm open to discussing it.

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by lemmih — APPROVED** [review]
I like it. Notes:

- I'm okay with ignoring databases that are newer than the current version of Forest. But I guess if we can open the database and the checks all pass, then it's probably fine.
- Creating a new database if something goes wrong sounds good. Starting from a clean snapshot is almost always better than failing.
- The development mode looks good.

**Comment by hanabi1224** [comment]
It's a bit weird to me to use the forest version as DB version since forest has more features than its DB and I would expect most of the version bumps are not DB related.  How about maintaining another DB version?  The CI check in the proposal could still catch when breaking changes are made to the DB but the version is not updated. For local development, one could freely change the DB until they bump the DB version and add a migration script

**Comment by lemmih** [comment]
I'm in favor of _not_ having a separate database version. It's easy to have useless version information. For example, actor and network versions are separate, but there's no benefit to this; it just causes more complexity. I would much rather use Forest versions for the database and have explicit null migrations between versions that do not change the DB layout. The sequence of migrations to get from version A to version B is still linear and unambiguous.

**Comment by LesnyRumcajs** [comment]
> Also a dedicated DB version makes it clear that every DB version bump should have a corresponding migration script, migrating a super old DB from v2 to v10 means running migration v3 to v10 in sequence. It's not very clear to me how to achieve this in the current plan

I tried to portray this in the [Checking if migration exists](https://github.com/ChainSafe/forest/blob/5d9ffaef3042f72096650b76ce5a3fe35aa4f6f4/documentation/src/developer_documentation/database_migrations.md#checking-if-migration-exists) section. While we may need a sequential upgrade (which could take a long time), we could have "shortcut" migrations in our migrations table. So a possible route would be `1--2--5--9--10`. A simple graph traversal algorithm would suffice.

**Review by hanabi1224 — APPROVED** [review]
@LesnyRumcajs Sounds good

**Comment by LesnyRumcajs** [comment]
I see no other objections; I'll move with the outlined plan to the implementation phase.

**Pull request merged**
