### PR TITLE
Use `CidHashMap` in the plain CAR-file blockstore

### LINKED ISSUE #3286: use `CidHashMap` in the plain CAR-file blockstore
**Issue summary**

The blockstore backed by an uncompressed CAR file uses two `HashMap`s with CIDs as keys: One map for the write cache and one map for the index. These maps should be replaced with `CidHashMap`, which uses less memory. Memory usage when validating a snapshot should be measured before and after the change.

Acceptance criteria:
- [ ] Add missing methods to `CidHashMap`
- [ ] Replace `HashMap<Cid, V>` with `CidHashMap<V>` in `car/plain.rs`
- [ ] Measure change in peak memory use when validating an uncompressed calibnet and mainnet snapshot. See `/usr/bin/time -v forest-cli snapshot validate {snapshot}.car`

**Other information and links**

https://github.com/ChainSafe/forest/blob/6dbd776c2e9f17323e2327a2523760e7f2130518/src/db/car/plain.rs#L152-L153

### PR DESCRIPTION
**Pull request by jdjaustin**
## Summary of changes

Changes introduced in this pull request:

Replace maps used for write cache and index in `src/db/car/plain.rs` with `CidHashMap`.

- [x] Add missing methods to `CidHashMap`
- [x] Replace `HashMap<Cid, V>` with `CidHashMap<V>` in `car/plain.rs`
- [x] Measure change in peak memory use when validating an uncompressed calibnet and mainnet snapshot. See `/usr/bin/time -v forest-cli snapshot validate {snapshot}.car`

## Reference issue to close (if applicable)

Closes #3286 

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by jdjaustin** [comment]
Running `gtime -v forest-cli snapshot validate forest_snapshot_calibnet_2023-08-01_height_786458.forest.car` with the latest changes from this PR (peak RSS 593760 kbytes) versus main branch (peak RSS 855152 kbytes):
Screen Shot 2023-08-01 at 4 12 34 PM
Screen Shot 2023-08-01 at 4 10 46 PM

**Comment by jdjaustin** [comment]
Running `gtime -v forest-cli snapshot validate 3095520_2023_08_04T18_00_00Z.car` with the latest changes from this PR (peak RSS 6432096 kbytes) versus main branch (peak RSS 6473984 kbytes):
Screen Shot 2023-08-04 at 6 47 39 PM
Screen Shot 2023-08-04 at 5 46 48 PM

**Comment by lemmih** [comment]
Better yet, use `forest-tool benchmark graph-traversal`

**Comment by lemmih** [comment]
I'm quite surprised by your numbers. They should be higher, and there should be a larger difference between your branch and `main`. These are the numbers I get:
`main/graph-traverse`: 13.26 GiB
`main/validate`: 17.74 GiB
`josh/graph-traverse`: 9.26 GiB
`josh/validate`: 13.75 GiB

I'll try running it on MacOS.

**Comment by jdjaustin** [comment]
My machine has done weird things ever since I got it. I recompiled this branch and ran it again against main; this time I'm getting much more expected results.
Screen Shot 2023-08-15 at 12 33 58 PM
Screen Shot 2023-08-15 at 12 03 46 PM

**Review by sudo-shashank — APPROVED** [review]

**Comment by jdjaustin** [comment]
I sense merge conflicts incoming due to #3388 merging soon, so converting this to draft until after I resolve those.

**Comment by ruseinov** [comment]
It would be nice to have some unit tests for the new CidHashMap functionality.

**Pull request merged**
