### PR TITLE
chore:interopnet&devnet:fix build error

### PR DESCRIPTION
**Pull request by detailyang**
Signed-off-by: detailyang <detailyang@gmail.com>

**Summary of changes**
Fix the build error when via `make interopnet` like the following:

```bash
   Compiling networks v0.1.0 (/Users/detailyang/art/github/detailyang/forest/types/networks)
error[E0659]: `UPGRADE_BREEZE_HEIGHT` is ambiguous (glob import vs glob import in the same module)
  --> types/networks/src/lib.rs:43:17
   |
43 |         height: UPGRADE_BREEZE_HEIGHT,
   |                 ^^^^^^^^^^^^^^^^^^^^^ ambiguous name
   |
note: `UPGRADE_BREEZE_HEIGHT` could refer to the constant imported here
  --> types/networks/src/lib.rs:16:9
   |
16 | pub use self::mainnet::*;
   |         ^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `UPGRADE_BREEZE_HEIGHT` to disambiguate
note: `UPGRADE_BREEZE_HEIGHT` could also refer to the constant imported here
  --> types/networks/src/lib.rs:21:9
   |
21 | pub use self::interopnet::*;

``` 

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

### CODE REVIEW

**Comment by detailyang** [comment]
Hello. It looks like the CI was failed because of the nightly build related (See PR #1154 ).

**Review by cryptoquick — APPROVED** [review]
Good catch! We'll be sure to get the CI PR pulled in as soon as its reviewed, but our broken nightly check won't block contributions.

**Comment by cryptoquick** [comment]
@detailyang Can you merge main onto this branch? It should resolve the CI issue.

**Review by ec2 — APPROVED** [review]

**Comment by ec2** [comment]
> 
> 
> @detailyang Can you merge main onto this branch? It should resolve the CI issue.

I can do that

**Comment by cryptoquick** [comment]
Great!
@detailyang Thank you for your contribution!

**Pull request merged**
