### PR TITLE
Remove support for `bls-signatures/pairing`

### LINKED ISSUE #1444: Support feature flag `bls-signatures/pairing`.
**Issue summary**

Right now we're forced to use `bls-signatures/blst` because `fvm` forces the feature.

**Other information and links**

The `fvm` crate in the `ref-fvm` repo should be updated to _not_ depend on `fvm_shared` with default-features. Opening a PR for `ref-fvm` would be preferable.

### PR DESCRIPTION
**Pull request by tyshko5**
**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes #1444

**Other information and links**

### CODE REVIEW

**Review by LesnyRumcajs — CHANGES_REQUESTED** [review]
I assume these: https://github.com/ChainSafe/forest/blob/main/Makefile#L76
should be now adapted and uncommented?

**Comment by tyshko5** [comment]
> I assume these: https://github.com/ChainSafe/forest/blob/main/Makefile#L76
> should be now adapted and uncommented?

I guess it should be deleted, since we support only blst

**Comment by LesnyRumcajs** [comment]
> > I assume these: https://github.com/ChainSafe/forest/blob/main/Makefile#L76
> > should be now adapted and uncommented?
> 
> I guess it should be deleted, since we support only blst

We have a feature `pairing`, so how come we don't support it?

**Comment by tyshko5** [comment]
> > > I assume these: https://github.com/ChainSafe/forest/blob/main/Makefile#L76
> > > should be now adapted and uncommented?
> > 
> > 
> > I guess it should be deleted, since we support only blst
> 
> We have a feature `pairing`, so how come we don't support it?

The whole point of the issue was to drop this support

**Comment by LesnyRumcajs** [comment]
> > > > I assume these: https://github.com/ChainSafe/forest/blob/main/Makefile#L76
> > > > should be now adapted and uncommented?
> > > 
> > > 
> > > I guess it should be deleted, since we support only blst
> > 
> > 
> > We have a feature `pairing`, so how come we don't support it?
> 
> The whole point of the issue was to drop this support

In your branch the project still exposes the `pairing` feature, so how is this support dropped?

**Comment by tyshko5** [comment]
> > > > > I assume these: https://github.com/ChainSafe/forest/blob/main/Makefile#L76
> > > > > should be now adapted and uncommented?
> > > > 
> > > > 
> > > > I guess it should be deleted, since we support only blst
> > > 
> > > 
> > > We have a feature `pairing`, so how come we don't support it?
> > 
> > 
> > The whole point of the issue was to drop this support
> 
> In your branch the project still exposes the `pairing` feature, so how is this support dropped?

Hope it doesn't now. If I'm wrong, please, let me know, where

**Comment by LesnyRumcajs** [comment]
> Hope it doesn't now. If I'm wrong, please, let me know, where

Well, `pairing = ["fvm_shared/pairing"]` exposes a feature in Forest and enables it in `fvm_shared`. So we still have it. If we still want it, my understanding is that relevant tests should be re-enabled and not deleted. If we don't want it, it should be deleted completely. Or am I missing something?

**Comment by tyshko5** [comment]
> > Hope it doesn't now. If I'm wrong, please, let me know, where
> 
> Well, `pairing = ["fvm_shared/pairing"]` exposes a feature in Forest and enables it in `fvm_shared`. So we still have it. If we still want it, my understanding is that relevant tests should be re-enabled and not deleted. If we don't want it, it should be deleted completely. Or am I missing something?

I'm talking about `bls-signatures/pairing` feature

**Comment by LesnyRumcajs** [comment]
@tyshko5 I don't really get your point. You removed a functionally empty crate flag that is a part of the global `pairing` feature. But it's not yet `not` supporting `pairing` at all. This is not done until you remove all the occurrences. This, or we support `pairing` (as stated in the PR title) and then we need to enable the commented-out tests which you partially deleted. I don't see anything in-between. We need to be thorough.

**Comment by tyshko5** [comment]
> @tyshko5 I don't really get your point. You removed a functionally empty crate flag that is a part of the global `pairing` feature. But it's not yet `not` supporting `pairing` at all. This is not done until you remove all the occurrences. This, or we support `pairing` (as stated in the PR title) and then we need to enable the commented-out tests which you partially deleted. I don't see anything in-between. We need to be thorough.

AFAI understand we need to stop supporting `bls-signatures/pairing` feature. AFAI understand I've deleted all of the occurrences of them. There are other `pairing ` features but they aren't concerning `bls-signatures` so I don't touch them

**Comment by LesnyRumcajs** [comment]
@tyshko5 Forest simply doesn't build right now with this feature on and to my understanding the goal is to make it either usable or delete the broken feature. Perhaps I'm missing something, I'll let others pronounce on this issue then.

**Comment by lemmih** [comment]
> > @tyshko5 I don't really get your point. You removed a functionally empty crate flag that is a part of the global `pairing` feature. But it's not yet `not` supporting `pairing` at all. This is not done until you remove all the occurrences. This, or we support `pairing` (as stated in the PR title) and then we need to enable the commented-out tests which you partially deleted. I don't see anything in-between. We need to be thorough.
> 
> AFAI understand we need to stop supporting `bls-signatures/pairing` feature. AFAI understand I've deleted all of the occurrences of them. There are other `pairing ` features but they aren't concerning `bls-signatures` so I don't touch them

They are all the `bls-signatures/pairing` feature. They should all be removed.

**Review by lemmih — APPROVED** [review]

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
