### PR TITLE
feat: increase the message request batch size from 4 to 8

### PR DESCRIPTION
**Pull request by lemmih**
## Summary of changes

Changes introduced in this pull request:

- Increase message batch size to match that of Lotus.
- Bump the tipset buffer size to `8*4=32` to avoid stalling when syncing calibnet.

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by LesnyRumcajs — COMMENTED** [review]
Did you notice any performance gains due to this change?

**Comment by lemmih** [comment]
> Did you notice any performance gains due to this change?

Syncing 1700 epochs went from 565s to 199s for me.

**Review by elmattic — APPROVED** [review]

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
> > Did you notice any performance gains due to this change?
> 
> Syncing 1700 epochs went from 565s to 199s for me.

That's fantastic! I want this!

**Comment by LesnyRumcajs** [comment]
> > > Did you notice any performance gains due to this change?
> > 
> > 
> > Syncing 1700 epochs went from 565s to 199s for me.
> 
> I think there's still room for a 2x improvement, btw. But that would be more involved than just tweaking a few buffer sizes.

By the way, have you tried other batch sizes, like 12 or 16? It might be worth to parameterize this.

**Comment by lemmih** [comment]
> > > > Did you notice any performance gains due to this change?
> > > 
> > > 
> > > Syncing 1700 epochs went from 565s to 199s for me.
> > 
> > 
> > I think there's still room for a 2x improvement, btw. But that would be more involved than just tweaking a few buffer sizes.
> 
> By the way, have you tried other batch sizes, like 12 or 16? It might be worth to parameterize this.

I haven't tried. Thank you for volunteering for this task. :)

**Pull request merged**
