### PR TITLE
forest-cli snapshot compress subcommand migration

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:

- Move snapshot compress subcommand to forest-tool

## Reference issue to close (if applicable)

Closes

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by hanabi1224 — APPROVED** [review]
Should we add some CI coverage for this feature? to `forest_tool_check.sh`.

**Comment by elmattic** [comment]
> forest_tool_check

We should add it more in `gen_coverage_report.sh`, no?

**Comment by hanabi1224** [comment]
Sorry I meant test coverage but it will be great to also have code coverage if feasible

**Review by lemmih — APPROVED** [review]

**Comment by elmattic** [comment]
> Sorry I meant test coverage but it will be great to also have code coverage if feasible

Will add both in a subsequent PR.

**Pull request merged**
