### PR TITLE
[automated] Update Lotus version in API tests

### PR DESCRIPTION
**Pull request by LeshyBot**
### Changes
- Updates Lotus version in the JSON-RPC API tests to the latest release.

### CODE REVIEW

**Review by lemmih — APPROVED** [review]

**Comment by hanabi1224** [comment]
Parity tests for `Filecoin.StateMinerPreCommitDepositForPower` is broken

```
2024-10-09T07:17:37.3037734Z Request dump: Request { method_name: "Filecoin.StateMinerPreCommitDepositForPower", params: Array [String("f0138097"), Object {"DealIDs": Null, "Expiration": Number(3055733), "SealProof": Number(8), "SealRandEpoch": Number(2004533), "SealedCID": Object {"/": String("bagboea4b5abcbp5d7ycbulzvf6ic73ab2zkeebeiasiyndbvpcl5zeqkk776uclm")}, "SectorNumber": Number(1990), "UnsealedCid": Null}, Array [Object {"/": String("bafy2bzaceaybqytxxdounajnsa7jgjtr4nkrzrlkdawoux2mgacpn6emeamas")}, Object {"/": String("bafy2bzacecqhuvzpreas6i5liaacfkp3wvrdcoqv4y5d4oggwxhhov4aq6cwe")}, Object {"/": String("bafy2bzaceaoeazbwlzzj55rzqm24chajk4x2wheksneshikm6yg4nqge56fmi")}, Object {"/": String("bafy2bzacecok4b4nj5mqwi2kgkrxfaetb7pdpdkliwqooy5ejcpdeaib557ua")}]], result_type: PhantomData<serde_json::value::Value>, api_paths: V1, timeout: 120s }
2024-10-09T07:17:37.3043281Z Request params JSON: ["f0138097",{"DealIDs":null,"Expiration":3055733,"SealProof":8,"SealRandEpoch":2004533,"SealedCID":{"/":"bagboea4b5abcbp5d7ycbulzvf6ic73ab2zkeebeiasiyndbvpcl5zeqkk776uclm"},"SectorNumber":1990,"UnsealedCid":null},[{"/":"bafy2bzaceaybqytxxdounajnsa7jgjtr4nkrzrlkdawoux2mgacpn6emeamas"},{"/":"bafy2bzacecqhuvzpreas6i5liaacfkp3wvrdcoqv4y5d4oggwxhhov4aq6cwe"},{"/":"bafy2bzaceaoeazbwlzzj55rzqm24chajk4x2wheksneshikm6yg4nqge56fmi"},{"/":"bafy2bzacecok4b4nj5mqwi2kgkrxfaetb7pdpdkliwqooy5ejcpdeaib557ua"}]]
2024-10-09T07:17:37.3047779Z Forest response: "343502843503823804794"
2024-10-09T07:17:37.3048942Z Lotus response: "34350284350382380479"
2024-10-09T07:17:37.3049691Z Diff: -"343502843503823804794"
2024-10-09T07:17:37.3050043Z 
2024-10-09T07:17:37.3050224Z +"34350284350382380479"
2024-10-09T07:17:37.3050514Z 
2024-10-09T07:17:37.3050521Z 
2024-10-09T07:17:37.3056918Z Request dump: Request { method_name: "Filecoin.StateMinerPreCommitDepositForPower", params: Array [String("f0138097"), Object {"DealIDs": Null, "Expiration": Number(3055733), "SealProof": Number(8), "SealRandEpoch": Number(2004533), "SealedCID": Object {"/": String("bagboea4b5abcbun7tqgnaiyq3sup5bb33zebqjlynkgrcbtoxg3sfn37ysc66bcd")}, "SectorNumber": Number(1989), "UnsealedCid": Null}, Array [Object {"/": String("bafy2bzacebba4hqc72yuuyziut43omsivdgzrfrvflmjyixyflzlknkkwibei")}, Object {"/": String("bafy2bzaceabdnjyoqte374ebwkfgyoq67yssfku26v6rmn5eipdtkuxcoslyg")}, Object {"/": String("bafy2bzacec3esagt4x4manbrvpczem67ssc5aqdojne5qzpfszoemme2hswkc")}]], result_type: PhantomData<serde_json::value::Value>, api_paths: V1, timeout: 120s }
2024-10-09T07:17:37.3066247Z Request params JSON: ["f0138097",{"DealIDs":null,"Expiration":3055733,"SealProof":8,"SealRandEpoch":2004533,"SealedCID":{"/":"bagboea4b5abcbun7tqgnaiyq3sup5bb33zebqjlynkgrcbtoxg3sfn37ysc66bcd"},"SectorNumber":1989,"UnsealedCid":null},[{"/":"bafy2bzacebba4hqc72yuuyziut43omsivdgzrfrvflmjyixyflzlknkkwibei"},{"/":"bafy2bzaceabdnjyoqte374ebwkfgyoq67yssfku26v6rmn5eipdtkuxcoslyg"},{"/":"bafy2bzacec3esagt4x4manbrvpczem67ssc5aqdojne5qzpfszoemme2hswkc"}]]
2024-10-09T07:17:37.3069781Z Forest response: "343502431473351305643"
2024-10-09T07:17:37.3070368Z Lotus response: "34350243147335130563"
2024-10-09T07:17:37.3071026Z Diff: -"343502431473351305643"
2024-10-09T07:17:37.3071354Z 
2024-10-09T07:17:37.3071508Z +"34350243147335130563"
2024-10-09T07:17:37.3071780Z 
2024-10-09T07:17:37.3071786Z 
```

**Comment by lemmih** [comment]
Oof. Either there's a regression in Lotus, or they fixed a bug.

**Comment by LesnyRumcajs** [comment]
@lemmih But you approved it! This means you volunteered to investigate it!

**Comment by LesnyRumcajs** [comment]
@lemmih It seems @LeshyBot "fixed" it. It's probably a particular event on the blockchain that triggered the issue and it would happen anyway. I believe the best course of action now is to upload the snapshot that fails the test and create an issue to investigate this behaviour.

**Comment by lemmih** [comment]
Tracking issue: https://github.com/ChainSafe/forest/issues/4879

I will update the issue once the snapshot upload has finished.

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
