### PR TITLE
Change default RPC port

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:

- Change default RPC port from `1234` to `2345`

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by lemmih** [comment]
@samuelarogbonlo We'll have to update forest-iac as well.

**Review by LesnyRumcajs — APPROVED** [review]
Let's mark it as a breaking change.

**Comment by elmattic** [comment]
> Let's mark it as a breaking change.

Where else should I do it? In the CHANGELOG it's in the `### Breaking` section.

**Comment by LesnyRumcajs** [comment]
> > Let's mark it as a breaking change.
> 
> Where else should I do it? In the CHANGELOG it's in the `### Breaking` section.

Ah, right, I didn't notice it. All good then.

**Review by jdjaustin — APPROVED** [review]

**Pull request merged**
