### PR TITLE
catch panic in `verify_window_post`

### PR DESCRIPTION
**Pull request by ec2**
**Summary of changes**
Changes introduced in this pull request:
- Fix handling of dispute_windowed_post in the event of an empty proof
- catch panic in `verify_window_post`

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

### CODE REVIEW

**Review by noot — APPROVED** [review]
hell ya

**Review by elmattic — APPROVED** [review]

**Comment by q9f** [comment]
Happy to include this in 0.2.0 if you can fix the tests and linter

**Comment by noot** [comment]
don't merge this yet - updating the rand version causes a state root mismatch

**Comment by q9f** [comment]
> don't merge this yet - updating the rand version causes a state root mismatch

is there no test for this?

**Comment by noot** [comment]
@q9f not right now, I have to manually sync the node to see if it's compatible with mainnet still. it would be nice to have an automated test for that

**Pull request merged**
