### PR TITLE
Fix shadowing of `msg` in closure

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:

- Fix shadowing of `msg` in closure
- Remove `Filecoin.StateCall` from filter list

```console
$ ./forest-tool api compare --lotus /ip4/127.0.0.1/tcp/1234/http --forest /ip4/127.0.0.1/tcp/2345/http forest_snapshot_calibnet_2024-03-18_height_1448006.forest.car.zst --filter StateCall -n 300
| RPC Method                | Forest | Lotus |
|---------------------------|--------|-------|
| Filecoin.StateCall (1231) | Valid  | Valid |
```

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by elmattic** [comment]
> 🤣

Also had a good laugh while looking for the culprit with git blame.

**Comment by elmattic** [comment]
> 🤣

Also had a good laugh while looking for the culprit with git blame.

From some reddit thread:
> Shadowing is indeed a bad idea in many languages, but Rust is different. (...).

Hmm.

**Comment by LesnyRumcajs** [comment]
`git blame` is a dangerous tool, not for the faint-hearted!

image

**Comment by LesnyRumcajs** [comment]
> Would it make sense to detect such shadowing errors by enabling clippy lints? 📎

In general I'm neutral to this. I like shadowing, it makes variable naming less of a hassle, and shadowing-errors are rare enough.

**Review by hanabi1224 — APPROVED** [review]

**Pull request merged**
