### PR TITLE
Pedantic Clippy `if_not_else` implementation

### PR DESCRIPTION
**Pull request by jdjaustin**
## Summary of changes

Changes introduced in this pull request:
- Add `-W clippy::if_not_else` to `lint` target in Makefile and changes to associated files to clear new clippy warnings.

## Reference issue to close (if applicable)

Closes associated task in #2420 

## Other information and links

Per the [Clippy Lints](https://rust-lang.github.io/rust-clippy/master/) documentation, "Negations reduce the readability of statements," and the code can easily be refactored to change these `if_not_else` statements to more readable `if_else` statements.

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is up-to-date. All user-facing changes should be reflected in this document.

### CODE REVIEW

**Comment by lemmih** [comment]
The `figure out if it's helpful and makes sense in our case` step is the hard part. Is `if_not_else` helpful and sensible in our case? If yes, add your arguments to the PR.

**Comment by lemmih** [comment]
@jdjaustin This lint isn't enabled by default. Can you explain the reasons why it isn't enabled by default and why those reasons don't apply to Forest?

**Comment by jdjaustin** [comment]
> @jdjaustin This lint isn't enabled by default. Can you explain the reasons why it isn't enabled by default and why those reasons don't apply to Forest?

The only thing I've found is that prior to October 2021, the `if_not_else` lint check was triggering false positives on `else if` statements, so perhaps that is why it isn't enabled by default. Is there some documentation somewhere that would help explain?

**Comment by lemmih** [comment]
> > @jdjaustin This lint isn't enabled by default. Can you explain the reasons why it isn't enabled by default and why those reasons don't apply to Forest?
> 
> The only thing I've found is that prior to October 2021, the `if_not_else` lint check was triggering false positives on `else if` statements, so perhaps that is why it isn't enabled by default. Is there some documentation somewhere that would help explain?

There's no documentation to read. It's not easy but you just have to look at the lint and try to feel what kind of changes it entails. Sometimes you can feel that the lint is always an improvement for our code-base. Other times, there might be too many false positives (eg cases where the lint shouldn't be applied) or the improvement is so small that it's not worth the added complexity or maybe it's too difficult to predict all the ways the lint will affect the code-base.

As an example, we recently enabled `unused_async`. It's disabled by default for two major reasons: (1) It's unstable, (2) there will be false positives where we can't remove async even though clippy thinks it is unused. Hubert reasoned that using an unstable lint isn't a big deal for us. And he reasoned that we don't mind manually marking each false positive. Keeping our async surface area as small as possible was worth the cost of the lint.

In general, if you aren't sure that we want a new lint then we don't want it. I'll close this PR.

**Pull request closed without merging**
