### PR TITLE
fix Grafana on MacOS

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
**Summary of changes**
Changes introduced in this pull request:
- change Grafana compose to work on both Linux and MacOS,
- listen on all interfaces by default for metrics endpoint. Security shouldn't be a concern here; it's up to the operator to configure the firewall properly.

**Reference issue to close (if applicable)**

Closes https://github.com/ChainSafe/forest/issues/2288

**Other information and links**

The issue stems from the fact that MacOS uses a thin VM for running docker. This doesn't work well with `host` network, and the ports should be exposed explicitly (which is not possible with `host` network). 

A way out of this is using `host.docker.internal`... which unfortunately exists only in Docker for MacOS (and probably in Docker for Windows). The way out of this is using a recently (2021) added `host-gateway`, see more https://github.com/docker/for-linux/issues/264#issuecomment-965465879. 

Tested on MacOS Ventura 13.01 and Linux Fedora Workstation 36.

### CODE REVIEW

**Comment by elmattic** [comment]
When this is RFR, I can test it and review it.

**Comment by LesnyRumcajs** [comment]
@elmattic Feel free to to test it on your end, be sure to recompile Forest to get it to listen on all interfaces for the metrics endpoint.

**Review by elmattic — APPROVED** [review]
Works perfectly now!

**Comment by LesnyRumcajs** [comment]
> Works perfectly now!

Thanks for looking into this and reporting it!

**Review by lemmih — APPROVED** [review]

**Pull request merged**
