### PR TITLE
hotfix:fix passphrase fake confirm

### PR DESCRIPTION
**Pull request by detailyang**
Signed-off-by: detailyang <detailyang@gmail.com>

**Summary of changes**
Fix the problem of inconsistent passwords when confirm the password:)

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

### CODE REVIEW

**Review by ec2 — APPROVED** [review]
Nice catch!

**Comment by cryptoquick** [comment]
Screenshot from 2021-06-15 09-00-57
Technically we already "incorrect passphrase" as an error. I'm not sure if we want a duplicate message?

**Comment by cryptoquick** [comment]
wait, nevermind, I just realized this is for when configuring a new keystore

**Review by cryptoquick — APPROVED** [review]
Haha, crap, yeah, the behavior we currently have is broken. Definitely a good catch!

**Pull request merged**
