### PR TITLE
fix: refactor known cid check logic

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

Changes introduced in this pull request:
- 

## Reference issue to close (if applicable)

Closes https://github.com/ChainSafe/forest/issues/2619

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is up-to-date. All user-facing changes should be reflected in this document.

### CODE REVIEW

**Comment by hanabi1224** [comment]
@lemmih kindly ping. Plz let me know if this refactoring looks OK and whether I should proceed or discard

**Comment by lemmih** [comment]
Looks good but the `actor_interface` is being moved to the `fil-actor-states` repository.

https://github.com/ChainSafe/fil-actor-states

**Comment by hanabi1224** [comment]
@lemmih I c, thanks. Then I will close this one and maybe PR it in the other repo if there's a chance

**Comment by LesnyRumcajs** [comment]
I want this! :heart: @hanabi1224

**Pull request closed without merging**
