### PR TITLE
FVM: Use ThreadedExecutor

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
## Summary of changes

Changes introduced in this pull request:

- use `ThreadedExecutor` given we don't guarantee 64 MiB of stack with Forest. See [ref-fvm changelog entry](https://github.com/filecoin-project/ref-fvm/blob/master/fvm/CHANGELOG.md?plain=1#L391-L392). This is also done in Lotus via [filecoin-ffi](https://github.com/filecoin-project/filecoin-ffi/blob/441fa8e61189dc32c2960c1f8d8ba56269f20366/rust/src/fvm/engine.rs#L179)
- remove `proofs` feature of `ref-fvm` given we don't use it anyway,
- ~~add `multicore-sdr` feature for `filecoin-proofs-api`. This could possibly improve performance. I added it because it's the default in [filecoin-ffi](https://github.com/filecoin-project/filecoin-ffi/blob/441fa8e61189dc32c2960c1f8d8ba56269f20366/rust/Cargo.toml#L62)~~ (it adds `hwloc` dependency which is a pain to resolve on Alpine, bailing to a separate issue https://github.com/ChainSafe/forest/issues/3757) 

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by lemmih — APPROVED** [review]
Not happy about all the `Arc`s, but I guess our arms are tied at the moment.

**Comment by LesnyRumcajs** [comment]
> Not happy about all the `Arc`s, but I guess our arms are tied at the moment.

Most of the `Arc`s are leftovers of something else, it's still a draft. ;)

**Review by lemmih — APPROVED** [review]

**Review by hanabi1224 — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
@lemmih @hanabi1224, mind approving again? I had to resolve a conflict in `Cargo.lock`.

**Review by lemmih — APPROVED** [review]

**Review by hanabi1224 — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
The `ThreadedExecutor` makes Forest hang in certain conditions.

```
❯ forest --chain calibnet --encrypt-keystore false --halt-after-import --height=-1000 --import-snapshot forest_snapshot_calibnet_2023-11-28_height_1129454.forest.car.zst
...
2023-11-29T08:39:21.746945Z  INFO forest_filecoin::state_manager: compute parent state height=1129263
...
6 hours later
...
TIMEOUT
```
See https://github.com/ChainSafe/forest/actions/runs/7021152381/job/19102821245?pr=3756

**Comment by LesnyRumcajs** [comment]
Superseded by https://github.com/ChainSafe/forest/pull/3766

**Pull request closed without merging**
