### PR TITLE
fix: cancel workflow event not trigger

### PR DESCRIPTION
**Pull request by hanabi1224**
**Summary of changes**

This is follow-up of https://github.com/ChainSafe/forest/pull/2012

Changes introduced in this pull request:
- filtering out `main` will cause the events never get triggered
- I looked at their code, it does not support filtering out branches ATM, so it will still cancel workflows triggered by commits to `main`, I can send out a PR to support the filtering, or we need to revert the previous change. (Note that PRs from forks will not be canceled then) @lemmih plz me know ur preference

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

### CODE REVIEW

**Comment by lemmih** [comment]
Can't you use `branches-ignore`?

**Comment by hanabi1224** [comment]
> Can't you use branches-ignore?

That's equivalent to branches: '!main'.  By looking at action logs, I found the event triggering branch is always `main`, so the event will never get triggered with this setup in the first place, another filtering needs to be implemented in action code

**Comment by lemmih** [comment]
Is the fix to add `if: ${{ github.event_name == 'pull_request' }}` to the `cancel-workflow-action` step?

**Comment by lemmih** [comment]
> No this is not pull request event but workflow_run event. We need to update the js code to check trigger branch name and whether it's from a fork

So a new version of `cancel-workflow-action` has to be released, right? Won't it be quicker to solve the issue on our end?

**Comment by hanabi1224** [comment]
> So a new version of cancel-workflow-action has to be released

The release of github action is quite like go module, it can be tag or commit revision. We can switch to my fork of the action after I test it before it's released.

**Comment by hanabi1224** [comment]
Hey @lemmih I have updated the PR with my fork version of the action. 
Here're my test results

ignore cancellation on push: https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220122632/jobs/5266413659
```
{
  eventName: 'workflow_run',
  sha: 'd815acf9[11](https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220122632/jobs/5266413659#step:2:12)104e9b9582bb98f5dbbb21d6c6cdd1',
  headSha: 'd815acf911104e9b9582bb98f5dbbb21d6c6cdd1',
  branch: 'main',
  owner: 'hanabi[12](https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220122632/jobs/5266413659#step:2:13)24',
  repo: 'test-cancel-workflow-action',
  GITHUB_RUN_ID: '32[20](https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220122632/jobs/5266413659#step:2:21)1[22](https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220122632/jobs/5266413659#step:2:23)632'
}
ignore_branches_on_push: ["main","master"]
Found token: yes
event: push, is_push: true
Ignore cancellation on push for branch: main
Cancel Complete.
```

cancel wf runs from fork PR:  https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220125182/jobs/5266419313
```
{
  eventName: 'workflow_run',
  sha: 'd815acf9[11](https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220125182/jobs/5266419313#step:2:12)104e9b9582bb98f5dbbb21d6c6cdd1',
  headSha: '6ec05[12](https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220125182/jobs/5266419313#step:2:13)35cf563edab630ce25876f0f2cdd1fcd0',
  branch: 'pr',
  owner: 'hanabi1224',
  repo: 'test-cancel-workflow-action',
  GITHUB_RUN_ID: '3220125182'
}
ignore_branches_on_push: ["main","master"]
Found token: yes
event: pull_request, is_push: false
Found workflow_id: ["37023448"]
Found 5 runs total.
Found 1 runs to cancel.
Canceling run:  {
  id: 3220115[14](https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220125182/jobs/5266419313#step:2:15)2,
  head_sha: 'e5d78de7fb284faacada0d8c61668238a4235760',
  status: 'in_progress',
  html_url: 'https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/32201[15](https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220125182/jobs/5266419313#step:2:16)142'
}
Cancel run 32[20](https://github.com/hanabi1224/test-cancel-workflow-action/actions/runs/3220125182/jobs/5266419313#step:2:21)115142 responded with status 202

Cancel Complete.
```

[Here](https://github.com/hanabi1224/test-cancel-workflow-action/blob/main/.github/workflows/cancel.yml) is the workflow definition in my test repo
```yaml
name: Cancel
on:
  workflow_run:
    workflows:
      - "main"
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: hanabi1224/cancel-workflow-action@120898519f2940069cc6a070c4f9c3d6cc2e7ff8
        with:
          workflow_id: ${{ github.event.workflow.id }}
          all_but_latest: true
          ignore_branches_on_push: |
            main
            master
```

**Review by lemmih — APPROVED** [review]
Looks like it works.

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
