### PR TITLE
Add more contextual information to wallet script

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

This PR brings some improvement to help with the debugging of #2726.

Changes introduced in this pull request:

- Log date and time just before sending the message.
- Log Forest mpool to verify that our message was correctly submitted. This also shows the message payload.
- Query the Glif API Node and check the presence of the message as well.

## Reference issue to close (if applicable)

Closes

## Other information and links

Sometimes, the cURL command produces `Broken pipe` errors. I don't know if we could get rid of those.

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by aatifsyed — CHANGES_REQUESTED** [review]
At this level of script complexity, I think it's worth moving this to `tests/`

See https://github.com/ChainSafe/forest/pull/3448

What infrastructure do you need to be able to migrate this test case?

**Review by LesnyRumcajs — COMMENTED** [review]
I'm unsure about relying on `glif.io` in our tests. It's a single point of failure and can be down or unreachable for any reason, blocking our CI as a result. 

Can we think of other approaches?

**Comment by elmattic** [comment]
> I'm unsure about relying on `glif.io` in our tests. It's a single point of failure and can be down or unreachable for any reason, blocking our CI as a result.

Could this `glif.io` check produce a failure that would block our CI? I'm asking this because this wasn't meant to be (in other words, what flags or shell command should be used for cURL to mitigate failures).
Basically, I would like to:
  - Use `glif` for troubleshooting the send issue
  - Once this goal is achieved, remove the `glif` check

I'm open to other approaches as well.

> 
> Can we think of other approaches?

**Comment by LesnyRumcajs** [comment]
> > I'm unsure about relying on `glif.io` in our tests. It's a single point of failure and can be down or unreachable for any reason, blocking our CI as a result.
> 
> Could this `glif.io` check produce a failure that would block our CI? I'm asking this because this wasn't meant to be (in other words, what flags or shell command should be used for cURL to mitigate failures). Basically, I would like to:
> 
> * Use `glif` for troubleshooting the send issue
> * Once this goal is achieved, remove the `glif` check
> 
> I'm open to other approaches as well.
> 
> > Can we think of other approaches?

At the very least, we could skip the check if `glif.io` or the RPC call is returning anything other than `200`.

**Comment by elmattic** [comment]
> > > I'm unsure about relying on `glif.io` in our tests. It's a single point of failure and can be down or unreachable for any reason, blocking our CI as a result.
> > 
> > 
> > Could this `glif.io` check produce a failure that would block our CI? I'm asking this because this wasn't meant to be (in other words, what flags or shell command should be used for cURL to mitigate failures). Basically, I would like to:
> > 
> > * Use `glif` for troubleshooting the send issue
> > * Once this goal is achieved, remove the `glif` check
> > 
> > I'm open to other approaches as well.
> > > Can we think of other approaches?
> 
> At the very least, we could skip the check if `glif.io` or the RPC call is returning anything other than `200`.

Sounds good.  But after giving some thought, we don't need to merge this code; just re-running the workflow until the error happens will be enough for me.

**Comment by LesnyRumcajs** [comment]
> Sounds good. But after giving some thought, we don't need to merge this code; just re-running the workflow until the error happens will be enough for me.

In that case, I'd recommend either running it in a loop in the script itself or make the entire job run multiple times (either copy-paste or perhaps use `strategy`) so you don't have to manually trigger it. Or do the same on a droplet to not exhaust GH workers.

**Comment by elmattic** [comment]
Closing it as I found out the message does not leave Forest node in case of failures.

**Pull request closed without merging**
