### PR TITLE
chore: assign the Forest team as owner of Forest

### PR DESCRIPTION
**Pull request by lemmih**
## Summary of changes

Changes introduced in this pull request:

- This will randomly assign two members of the Forest team (excluding admins, executives, and Lee).

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
I'm not sure about assigning non-dev folks is useful. Can we create another group, like `forest-core` or `forest-devs`?

**Comment by lemmih** [comment]
> I'm not sure about assigning non-dev folks is useful. Can we create another group, like `forest-core` or `forest-devs`?

I've configured a subset of the Forest team to be eligible for review selection. Lee, Samual, Afri, etc, are exempted.

**Comment by LesnyRumcajs** [comment]
> > I'm not sure about assigning non-dev folks is useful. Can we create another group, like `forest-core` or `forest-devs`?
> 
> I've configured a subset of the Forest team to be eligible for review selection. Lee, Samuel, Afri, etc, are exempted.

Let's update the PR description, then.

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by lemmih** [comment]
> > > I'm not sure about assigning non-dev folks is useful. Can we create another group, like `forest-core` or `forest-devs`?
> > 
> > 
> > I've configured a subset of the Forest team to be eligible for review selection. Lee, Samuel, Afri, etc, are exempted.
> 
> Let's update the PR description, then.

Oh geez, yes, I meant to write `excluding` rather than `including`.

**Review by creativcoder — APPROVED** [review]

**Pull request merged**
