### PR TITLE
ci: fix gh pages action version string

### PR DESCRIPTION
**Pull request by q9f**
I must have fatfingered this 🙄

### CODE REVIEW

**Review by lemmih — APPROVED** [review]

**Comment by lemmih** [comment]
Oh, we also need to restore the `scripts/build-rust-docs.sh` script or inline it.

**Review by lemmih — CHANGES_REQUESTED** [review]
Think I accidentally deleted `scripts/build-rust-docs.sh`.

**Review by lemmih — CHANGES_REQUESTED** [review]
Oh, we don't need the script. That entire section should just be removed from the workflow.

**Comment by q9f** [comment]
#1383

**Pull request closed without merging**
