### PR TITLE
fix: move cancel-workflow-action to its own yml and allow cancelling workflows triggered by fork repo PRs

### PR DESCRIPTION
**Pull request by hanabi1224**
**Summary of changes**
Changes introduced in this pull request:
- Cancel stale workflow runs triggered by PRs from fork repos, following the [instruction here](https://github.com/styfle/cancel-workflow-action#advanced-pull-requests-from-forks)
- Use `all_but_latest: true` to also cancel queued workflow runs, following the [instruction here](https://github.com/styfle/cancel-workflow-action#advanced-all-but-latest)

**Reference issue to close (if applicable)**

Closes https://github.com/ChainSafe/forest/issues/1988

**Other information and links**

### CODE REVIEW

**Comment by hanabi1224** [comment]
@lemmih Not sure why the new workflow is not triggered as usual, does it require any special setting changes for this repo?

**Comment by lemmih** [comment]
> @lemmih Not sure why the new workflow is not triggered as usual, does it require any special setting changes for this repo?

Hmm, not that I know off.

**Comment by lemmih** [comment]
> @lemmih Not sure why the new workflow is not triggered as usual, does it require any special setting changes for this repo?

You have write access to the repository. You could try pushing your branch to the forest repo and see if that changes anything.

**Comment by hanabi1224** [comment]
@lemmih according to [this answer](https://github.com/orgs/community/discussions/25288), the workflow needs to lands on the default or `main` branch first before the event can be triggered. It's kinda chicken and egg, but we have a similar [workflow](https://github.com/ChainSafe/mina-rs/actions/workflows/cancel-stale.yml) setup for mina that worked fine before.

> Is the workflow “GitHub Linux Release” existing on the master or default branch?
To trigger a workflow runs on the workflow_run event, the workflow file should exist on the master or default branch.

**Review by tyshko5 — APPROVED** [review]

**Comment by hanabi1224** [comment]
It does not seem to work, looking

**Pull request merged**
