### PR TITLE
Deletes reimports of Ipld struct

### PR DESCRIPTION
**Pull request by tyshko5**
**Summary of changes**
Changes introduced in this pull request:
- Deletes reimports of Ipld struct

**Reference issue to close (if applicable)**

**Other information and links**

### CODE REVIEW

**Comment by lemmih** [comment]
Can we close this draft PR?

**Comment by tyshko5** [comment]
> Can we close this draft PR?

It is a bit useful, and small, so I'd rather merge it

**Comment by lemmih** [comment]
> > Can we close this draft PR?
> 
> It is a bit useful, and small, so I'd rather merge it

Is it related to issue #1700 ? Could you update the "summary of changes", please?

**Comment by lemmih** [comment]
I'm not sure this is worthwhile. We do want to eliminate all of the re-exports but that's be handled in larger PRs, I think.

**Comment by tyshko5** [comment]
Always thought smaller PR to be better than bigger ones

**Comment by lemmih** [comment]
> Always thought smaller PR to be better than bigger ones

Well, sure. But you have to re-write the title of this issue and write a summary of the changes. Then we can review it.

**Comment by tyshko5** [comment]
Done

**Review by lemmih — APPROVED** [review]

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
