### PR TITLE
Restore `--tipset` flag to snapshot export command

### LINKED ISSUE #2999: Restore `--tipset` functionality to `forest-cli snapshot export`
**Issue summary**

The `--tipset` flag was removed as part of PR #2638 but we still need this functionality to compare Forest snapshot exports byte-for-byte with Lotus snapshot exports; the approach has been to download a Lotus snapshot, then export the Forest snapshot at the exact same height using the `--tipset` flag with `forest-cli snapshot export`.

**Other information and links**

Here is the exact location where the `--tipset` flag previously appared in the codebase: https://github.com/ChainSafe/forest/pull/2638/files#diff-a302ffc3bbc97bbfc1a2ce05d64d36ee32b6c9dbf285a318cec375e71735f947L40

### PR DESCRIPTION
**Pull request by jdjaustin**
## Summary of changes

Changes introduced in this pull request:

- Restore `--tipset` flag functionality to allow snapshot export at a certain epoch.
- Added a step to print a newline to the terminal after snapshot export is complete to partially address issue #3171.

## Reference issue to close (if applicable)

Closes #2999 and #3171

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by jdjaustin** [comment]
Forest and Lotus snapshot sizes are a few hundred bytes different, similar to the status of snapshots prior to PR #2540. Haven't pinpointed a cause yet.

**Comment by lemmih** [comment]
> Forest and Lotus snapshot sizes are a few hundred bytes different, similar to the status of snapshots prior to PR #2540. Haven't pinpointed a cause yet.

Are you comparing the compressed files or uncompressed files?

**Comment by ruseinov** [comment]
> Forest and Lotus snapshot sizes are a few hundred bytes different, similar to the status of snapshots prior to PR #2540. Haven't pinpointed a cause yet.

Could have something to do with this: https://github.com/ChainSafe/forest/pull/3015 ?

**Comment by jdjaustin** [comment]
> > Forest and Lotus snapshot sizes are a few hundred bytes different, similar to the status of snapshots prior to PR #2540. Haven't pinpointed a cause yet.
> 
> Are you comparing the compressed files or uncompressed files?

Compressed.

**Comment by jdjaustin** [comment]
> > Forest and Lotus snapshot sizes are a few hundred bytes different, similar to the status of snapshots prior to PR #2540. Haven't pinpointed a cause yet.
> 
> Could have something to do with this: #3015 ?

Yes, that might be it. I'll re-check now that that change has been merged.

**Comment by jdjaustin** [comment]
(Uncompressed) Forest snapshot is still larger than (uncompressed) Lotus snapshot by a few hundred bytes.

**Comment by lemmih** [comment]
> (Uncompressed) Forest snapshot is still larger than (uncompressed) Lotus snapshot by a few hundred bytes.

Try using the [`ipfs`](https://docs.ipfs.tech/how-to/command-line-quick-start/) tool to inspect the CAR files. Something like `ipfs dag import` and then `ipfs dag stat`.

**Comment by jdjaustin** [comment]
Leaving notes for future-me here. Had to use [this hack](https://discuss.ipfs.tech/t/repo-seems-stuck-at-yet-unexisting-version-14-and-cannot-revert-migration-solved-with-a-hack/14911) to manually edit the `~/.ipfs/version` to `13` due to program/repo version mismatch. Also need to use `--allow-big-block` flag with `ipfs dag import`.

**Comment by jdjaustin** [comment]
> > (Uncompressed) Forest snapshot is still larger than (uncompressed) Lotus snapshot by a few hundred bytes.
> 
> Try using the [`ipfs`](https://docs.ipfs.tech/how-to/command-line-quick-start/) tool to inspect the CAR files. Something like `ipfs dag import` and then `ipfs dag stat`.

Do you know how long the `ipfs dag import` step should take for a calibnet snapshot? I let it run overnight and it still hadn't finished this morning. Since I already had an older version of ipfs installed and had some issues with getting this command running, I might just try on a fresh droplet.

**Comment by lemmih** [comment]
> > > (Uncompressed) Forest snapshot is still larger than (uncompressed) Lotus snapshot by a few hundred bytes.
> > 
> > 
> > Try using the [`ipfs`](https://docs.ipfs.tech/how-to/command-line-quick-start/) tool to inspect the CAR files. Something like `ipfs dag import` and then `ipfs dag stat`.
> 
> Do you know how long the `ipfs dag import` step should take for a calibnet snapshot? I let it run overnight and it still hadn't finished this morning. Since I already had an older version of ipfs installed and had some issues with getting this command running, I might just try on a fresh droplet.

I wouldn't expect it to take more than a few seconds.

**Comment by lemmih** [comment]
@jdjaustin You can also use this tool: https://github.com/ipld/go-car/tree/master/cmd/car

**Review by lemmih — APPROVED** [review]

**Review by hanabi1224 — APPROVED** [review]

**Review by creativcoder — APPROVED** [review]

**Pull request merged**
