### PR TITLE
[WIP] IpldJson Property Test

### PR DESCRIPTION
**Pull request by jdjaustin**
**Summary of changes**
Changes introduced in this pull request:
- Use quickcheck to test our custom implementations of `IpldJson`

**Reference issue to close (if applicable)**

Closes associated task in #1881 

**Other information and links**

N/A

### CODE REVIEW

**Comment by lemmih** [comment]
Remember not to use `forest_test_utils::to_string_with` when you have `*Json` structures. Let those structures do the heavy lifting for you.

**Comment by jdjaustin** [comment]
> Remember not to use `forest_test_utils::to_string_with` when you have `*Json` structures. Let those structures do the heavy lifting for you.

I removed the `forest_test_utils` macros, and even though I have tried several different things, it seems like the same problem is occurring with the test; the LHS of the comparison is giving a number that's not in scientific notation while the RHS is giving a number that is in scientific notation. Not sure if it's an issue with the test or the way `IpldJson` is serialized/deserialized...

**Comment by lemmih** [comment]
JSON cannot natively represent i128 numbers. We could use a scheme like `BYTES_JSON_KEY` for numbers that can't fit in an `i64`.

**Comment by lemmih** [comment]
@jdjaustin Maybe we don't even want a json serializer for `Ipld`. If it is only used for debugging then we can just remove it and rely on `Debug` instead.

**Comment by jdjaustin** [comment]
> @jdjaustin Maybe we don't even want a json serializer for `Ipld`. If it is only used for debugging then we can just remove it and rely on `Debug` instead.

How can I verify if it is only used for debugging?

**Comment by lemmih** [comment]
> > @jdjaustin Maybe we don't even want a json serializer for `Ipld`. If it is only used for debugging then we can just remove it and rely on `Debug` instead.
> 
> How can I verify if it is only used for debugging?

First you delete the deserializer. If nothing breaks then it is unused. Otherwise you look at what breaks and check if it is debugging code or not.

**Comment by jdjaustin** [comment]
See #2072

**Pull request closed without merging**
