### PR TITLE
Minor fixes and touch-ups

### PR DESCRIPTION
**Pull request by huitseeker**
While reading the code:
- Option / Result pattern modifications,
- Rust edition updates (e.g. -> panic!)
- classic clippy-like fixes

### CODE REVIEW

**Review by cryptoquick — APPROVED** [review]
Really good minor style improvements! I don't see anything here that'd alter behavior significantly.

@ec2 @creativcoder @olibearo I think we should get this merged sooner rather than later. It touches a lot of code and it'd suck if this got stale.

**Comment by ec2** [comment]
It looked good to me. I just need to build and run it to make sure there are no functional regressions. Will do that tonight.

**Comment by cryptoquick** [comment]
Sounds great, glad you're doing that, @ec2

**Review by ec2 — APPROVED** [review]

**Comment by ec2** [comment]
LGTM. Thanks so much for taking the time to have a gander at Forest <3

**Pull request merged**
