### PR TITLE
Remove legacy_amt and use upstream amt

### PR DESCRIPTION
**Pull request by creativcoder**
## Summary of changes

Changes introduced in this pull request:
- 

## Reference issue to close (if applicable)

Closes 

## Change checklist

- [x] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is up-to-date. All user-facing changes should be reflected in this document.

### CODE REVIEW

**Review by LesnyRumcajs — APPROVED** [review]
Obliterated

**Comment by lemmih** [comment]
I will test on mainnet before reviewing.

**Review by hanabi1224 — APPROVED** [review]

**Review by tyshko5 — APPROVED** [review]

**Comment by lemmih** [comment]
@creativcoder Is this ready to merge?

**Comment by creativcoder** [comment]
yes

**Pull request merged**
