### PR TITLE
forest-cli archive export/ checkpoints subcommands migration

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:

- Move remaining archive subcommands to forest-tool

## Reference issue to close (if applicable)

Closes

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by elmattic** [comment]
Not sure why `importing_bad_snapshot_should_fail` is failing and if I could ignore and just re-run the job.
Locally the test was failing as well, then re-running it again it's ✅.

**Review by lemmih — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
@elmattic what was the failure for the test? It should not be flaky at all.

**Comment by elmattic** [comment]
> @elmattic what was the failure for the test? It should not be flaky at all.

Test was too slow and resulted in a time out.

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
> > @elmattic what was the failure for the test? It should not be flaky at all.
> 
> Test was too slow and resulted in a time out.

Let's create an issue if it happens more often.

**Pull request merged**
