### PR TITLE
feat(p2p): bootstrap node specific configurations

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

(Part of https://github.com/ChainSafe/forest/issues/4346 investigation)

This PR adds `--bootstrap` CLI option to forest daemon and configure the P2P parameters differently, to align with lotus.

Changes introduced in this pull request:

- adds `--bootstrap` CLI option to forest daemon
- update gossipsub configs to align with lotus
- implement bootstrap node specific P2P configs that align with lotus

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by LesnyRumcajs — COMMENTED** [review]
Is there a reason for running a stateless node outside of being a bootstrap node? If not, let's coalesce `stateless` and `bootstrap` notion into a single one, probably `bootstrap` for better discoverability. This will require some changes in docs, but should be easy to find.

**Comment by hanabi1224** [comment]
> Is there a reason for running a stateless node outside of being a bootstrap node? If not, let's coalesce `stateless` and `bootstrap` notion into a single one, probably `bootstrap` for better discoverability. This will require some changes in docs, but should be easy to find.

@LesnyRumcajs As I understand, the bootstrap-specific gossipsub config mainly works for regular(stateful) nodes. For stateless nodes, I need to explore further on whether it works better with the bootstrap config or the non-bootstrap config as lotus does not offer the stateless mode atm.

**Comment by LesnyRumcajs** [comment]
@hanabi1224 Did you confirm the mainnet node (both `bootstrap` and not `bootstrap`) works well with those settings? I don't understand what each of those parameters does, so it'd be great to manually check we're still good on connectivity side.

What should we actually expect by applying these settings? Better connectivity? Better performance?

Should this be documented so that the infrastructure team can benefit from this flag?

**Comment by LesnyRumcajs** [comment]
@hanabi1224 what do we do with this draft?

**Comment by LesnyRumcajs** [comment]
> @hanabi1224 what do we do with this draft?

bump

**Comment by hanabi1224** [comment]
Closing for now.

**Pull request closed without merging**
