### PR TITLE
Deduce network type from daemon and set cli config

### LINKED ISSUE #2609: forest-cli - deduce network type
**Issue summary**

Currently, we need to add `--chain calibnet` to a bunch of `forest-cli` subcommands. This is not required for most, except, e.g., `snapshot fetch`, which does not require a running node.

Instead, we could ask the Forest daemon via RPC what network it runs. Then do tricks like [here](https://github.com/ChainSafe/forest/blob/main/forest/cli/src/subcommand.rs#L8-L10) based on that.

**Task summary**

- [X] Figure out how to get the network type via RPC call. Something may already be available.
- [X] Don't use the explicit flag in subcommands that communicate with the daemon over RPC,
- [X] The `Address` trick above shouldn't require an explicit flag as well.

**Acceptance Criteria**

- [X] `--chain calibnet` is not required for commands that use the RPC daemon endpoint,
- [X] mainnet is also correctly deduced,
- [X] a basic integration test showing that this works as expected (simply removing the `--chain calibnet` from `forest-cli sync wait` in the CI will do).

**Other information and links**

### PR DESCRIPTION
**Pull request by sudo-shashank**
## Summary of changes

Changes introduced in this pull request:
- Identify network type from forest daemon for `forest-cli` subcommands

## Reference issue to close (if applicable)

Closes #2609 

## Change checklist

- [X] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation,
- [X] I have added tests that prove my fix is effective or that my feature works (if possible),
- [X] I have made sure the [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is up-to-date. All user-facing changes should be reflected in this document.

### CODE REVIEW

**Review by lemmih — CHANGES_REQUESTED** [review]
Hmm, doing this right will probably require re-thinking the way we handle CLI options. Let's shelve this for now.

**Comment by lemmih** [comment]
More specifically, the client should have an option for `--rpc false`. That makes no sense. And we need to re-think the `--chain` flag.

**Comment by LesnyRumcajs** [comment]
@lemmih I'd still merge it for now. It kind of is an improvement over what we have now - some obscure serialisation error if the client and the daemon don't match.

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by lemmih** [comment]
> @lemmih I'd still merge it for now. It kind of is an improvement over what we have now - some obscure serialisation error if the client and the daemon network don't match. It's not ideal and moving forward we should prioritise implementing the new architecture proposed some time ago. Or come up with another and implement it.

But we just replaced one set of obscure errors for another. If you try to validate a snapshot without using the `--rpc false` flag, forest-cli will fail badly.

**Comment by lemmih** [comment]
@sudo-shashank If we change this PR to only query the daemon when it's actually required then I'll re-review.

**Review by lemmih — APPROVED** [review]
Approved.

This PR solves our immediate problems but the CLI situation is still a mess and will need some love at a later point in time.

**Pull request merged**
