### PR TITLE
fix: return null in `MinerGetBaseInfo` if miner hasn't been around for 900 epochs

### PR DESCRIPTION
**Pull request by lemmih**
## Summary of changes

Changes introduced in this pull request:

- If a miner isn't found in the look-back state, we must return `null` to match Lotus' behavior.

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
@lemmih In general, can we synthesize a test that would fail without this change? This is to ensure the behaviour doesn't change by chance in the future.

**Comment by lemmih** [comment]
Testing it using one of the devnets is possible in theory but rather tricky. It'll be much easier once we have #4657.

**Review by ruseinov — APPROVED** [review]

**Comment by lemmih** [comment]
Oof, more intermittent networking errors.

**Comment by LesnyRumcajs** [comment]
The CI just doesn't want this PR to be merged and finds plethora of excuses. :)

**Pull request merged**
