### PR TITLE
chore: upgrade rust toolchain to 1.69.0-nightly

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

Changes introduced in this pull request:
- upgrade rust toolchain to 1.69.0-nightly (e972bc808 2023-01-29)
- all code changes come from `cargo clippy --fix` and `cargo fmt`

## Reference issue to close (if applicable)

Closes 

## Other information and links

Rust 1.67.0 has been released on 26 January, 2023 https://releases.rs/docs/1.67.0/

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is up-to-date. All user-facing changes should be reflected in this document.

### CODE REVIEW

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by hanabi1224** [comment]
@LesnyRumcajs Looks like we need to have @LeshyBot to sign the CLA

**Comment by LesnyRumcajs** [comment]
@hanabi1224 I signed it a few hours ago, I guess that one comment is a dangling one. See the CI run (it's green).

**Comment by hanabi1224** [comment]
@LesnyRumcajs Awesome, thanks!

**Review by creativcoder — APPROVED** [review]

**Review by elmattic — APPROVED** [review]
Works for my target (`nightly-2023-01-30-aarch64-apple-darwin`).

**Pull request merged**
