### PR TITLE
feat: forest-tool snapshot heaviest-tipset

### PR DESCRIPTION
**Pull request by aatifsyed**

### CODE REVIEW

**Comment by aatifsyed** [comment]
> ```
> root@aatifsyed-behind-the-code-xl:~# date && time ./custom-build/forest-tool snapshot heaviest-tipset ./filops_snapshot_mainnet_2023-09-07_height_3192720.car.zst && date
> Fri Sep  8 11:05:41 UTC 2023
> Killed
> 
> real    5m10.553s
> user    4m10.746s
> sys     0m59.395s
> ```
> 
> Some kind of bug?

```console
root@aatifsyed-behind-the-code-xl:~# dmesg -T| grep -E -i -B5 'killed process'
...
[Fri Sep  8 11:20:42 2023] [   6655]     0  6655     1547      180    45056        0             0 sleep
[Fri Sep  8 11:20:42 2023] [   6659]     0  6659     3856      990    73728        0             0 sshd
[Fri Sep  8 11:20:42 2023] [   6660]     0  6660     3856     1039    69632        0             0 sshd
[Fri Sep  8 11:20:42 2023] [   6661]   109  6661     3856      639    69632        0             0 sshd
[Fri Sep  8 11:20:42 2023] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-0.slice/session-28.scope,task=forest-tool,pid=6633,uid=0
[Fri Sep  8 11:20:42 2023] Out of memory: Killed process 6633 (forest-tool) total-vm:169013872kB, anon-rss:64978596kB, file-rss:2112kB, shmem-rss:0kB, UID:0 pgtables:193264kB oom_score_adj:0
```

**Comment by lemmih** [comment]
> > ```
> > root@aatifsyed-behind-the-code-xl:~# date && time ./custom-build/forest-tool snapshot heaviest-tipset ./filops_snapshot_mainnet_2023-09-07_height_3192720.car.zst && date
> > Fri Sep  8 11:05:41 UTC 2023
> > Killed
> > 
> > real    5m10.553s
> > user    4m10.746s
> > sys     0m59.395s
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Some kind of bug?
> 
> ```
> root@aatifsyed-behind-the-code-xl:~# dmesg -T| grep -E -i -B5 'killed process'
> ...
> [Fri Sep  8 11:20:42 2023] [   6655]     0  6655     1547      180    45056        0             0 sleep
> [Fri Sep  8 11:20:42 2023] [   6659]     0  6659     3856      990    73728        0             0 sshd
> [Fri Sep  8 11:20:42 2023] [   6660]     0  6660     3856     1039    69632        0             0 sshd
> [Fri Sep  8 11:20:42 2023] [   6661]   109  6661     3856      639    69632        0             0 sshd
> [Fri Sep  8 11:20:42 2023] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-0.slice/session-28.scope,task=forest-tool,pid=6633,uid=0
> [Fri Sep  8 11:20:42 2023] Out of memory: Killed process 6633 (forest-tool) total-vm:169013872kB, anon-rss:64978596kB, file-rss:2112kB, shmem-rss:0kB, UID:0 pgtables:193264kB oom_score_adj:0
> ```

Opening a `.car.zst` requires the entire file to be decompressed. Right now, we decompress it in memory.

**Comment by lemmih** [comment]
You can read the roots of the CAR file without opening it as a blockstore. How will you use this command?

**Comment by aatifsyed** [comment]
> You can read the roots of the CAR file without opening it as a blockstore. How will you use this command?

I didn't know that :) 
`lotus-shed sync validate <TSK>`
I was trying to get TSK

**Pull request closed without merging**
