### PR TITLE
chore: Redesign the Forest node Grafana dashboard. 

### PR DESCRIPTION
**Pull request by samuelarogbonlo**
## Summary of changes

Changes introduced in this pull request:

- Redesign the Forest node Grafana dashboard. It's currently being displayed at this public [url](https://chainsafe.grafana.net/public-dashboards/147b51603dbb4eddaff1d5d9eedf23dc)

## Reference issue to close (if applicable)

Closes

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by LesnyRumcajs — APPROVED** [review]
I'd change monotonically increasing metrics to counters, e.g., p2p messages. Otherwise LGTM.

**Review by hanabi1224 — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
> > I'd change monotonically increasing metrics to counters, e.g., p2p messages. Otherwise LGTM.
> 
> @LesnyRumcajs, i have made some changes please can you Public Url listed in the description.

Looks good, I'd also change the `Range Sync Failure Count` to counter.

**Comment by samuelarogbonlo** [comment]
> @samuelarogbonlo Also, could you please change the time range to several days? Otherwise it's hard to spot any trends. Or perhaps this could be made variable? I recall it was possible with public DataDog dashboards.

@LesnyRumcajs unfortunately, template variables are not supported for public dashboards on Grafana cloud but i have set the time range to 7 days.

**Comment by samuelarogbonlo** [comment]
@LesnyRumcajs can you reapprove?

**Pull request merged**
