### PR TITLE
chore: update calibnet tipset checkpoint

### PR DESCRIPTION
**Pull request by creativcoder**
**Summary of changes**
Changes introduced in this pull request:
- Move checkpoint closer to current snapshot head.

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

### CODE REVIEW

**Review by LesnyRumcajs — APPROVED** [review]
I wonder if we could do this in a somehow more automated way.

**Comment by creativcoder** [comment]
> We might wanna keep the old checkpoints. It'll help us load older snapshots when testing migrations.
> 
> Could you also add a new checkpoint for mainnet?

Done

**Comment by creativcoder** [comment]
> I wonder if we could do this in a somehow more automated way.

Ah we could move these checkpoints to a file and read and update based on snapshot filename conditionally. I'll look into how feasible it would be. Also to note that it's not something we'd do frequently.

**Review by lemmih — APPROVED** [review]

**Comment by lemmih** [comment]
Maybe we should make it part of the release checklist to add new checkpoints.

**Pull request merged**
