### PR TITLE
Property Test for Cid

### PR DESCRIPTION
**Pull request by jdjaustin**
**Summary of changes**
Changes introduced in this pull request:
- Use quickcheck to test our custom implementations of `Cid`

**Reference issue to close (if applicable)**

Closes associated task in #1881 

**Other information and links**

N/A

### CODE REVIEW

**Review by lemmih — APPROVED** [review]
`cid` does implement `quickcheck::Arbitrary` but unfortunately they are using a dated version of quickcheck. :-/

**Review by LesnyRumcajs — COMMENTED** [review]
The same comment as for the `BigInt` test. I don't see a value-added here. If we want to make sure `Cid` serializes/deserializes properly, we should open a PR to `ref-fvm` or wherever that type is defined and not test it in its clients.

**Comment by lemmih** [comment]
> The same comment as for the `BigInt` test. I don't see a value-added here. If we want to make sure `Cid` serializes/deserializes properly, we should open a PR to `ref-fvm` or wherever that type is defined and not test it in its clients.

Neither `ref-fvm` nor `cid` defines the custom JSON serialization that we require. As long as we have a custom serializer/de-serializer, we need to test that it is lossless. It would be great if we didn't need this JSON serialization code at all, though.

**Comment by LesnyRumcajs** [comment]
I guess it's the same issue, this PR is not testing what is supposed to do, as you noted here? https://github.com/ChainSafe/forest/pull/1982#issuecomment-1265150779

**Comment by lemmih** [comment]
@jdjaustin Like with the other PR, explicitly use the `serialize` and `deserialize` functions.

**Review by lemmih — CHANGES_REQUESTED** [review]
Test the custom serialization functions.

**Review by lemmih — APPROVED** [review]

**Review by tyshko5 — APPROVED** [review]

**Pull request merged**
