### PR TITLE
[Fix] Cargo.lock package version

### PR DESCRIPTION
**Pull request by ruseinov**
Fixes the `release_checklist.md` and includes `Cargo.lock` package version update.

### CODE REVIEW

**Review by aatifsyed — CHANGES_REQUESTED** [review]
I don't think this is the right approach - change CI to fail by using `cargo build --locked`

**Comment by ruseinov** [comment]
> I don't think this is the right approach - change CI to fail by using `cargo build --locked`

We are already doing `cargo install --locked` and that obviously does not help.

**Comment by aatifsyed** [comment]
I think we want this in CI:
```
cargo generate-lockfile --locked
```

**Comment by ruseinov** [comment]
> cargo generate-lockfile --locked

We definitely don't want that here, it fails with the latest `Cargo.lock`. Let's fix it properly outside of the scope of this PR.

**Review by lemmih — APPROVED** [review]

**Review by aatifsyed — APPROVED** [review]

**Pull request merged**
