### PR TITLE
chore: do not build libzstd-sys by default

### PR DESCRIPTION
**Pull request by hanabi1224**
**Summary of changes**
Changes introduced in this pull request:
- make `rocksdb` compression types optional
- exclude `rocksdb/zstd` from default features to reduce build time cuz it's one of the slowest, see table in https://github.com/ChainSafe/forest/pull/2089
- improve tests

**Reference issue to close (if applicable)**

Closes part of https://github.com/ChainSafe/forest/issues/2088

**Other information and links**

### CODE REVIEW

**Comment by lemmih** [comment]
I'm not sure the `rocksdb/io-uring` feature is stable enough that we should include it.

**Comment by lemmih** [comment]
> I'm not sure the `rocksdb/io-uring` feature is stable enough that we should include it.

Or maybe it would be simple enough to install liburing on the CI servers.

**Review by lemmih — APPROVED** [review]
Lovely. It's tempting to go even further and disable `snappy`, `zlib` and `bzip2` by default.

**Review by LesnyRumcajs — COMMENTED** [review]
I feel we should have some piece of documentation that complements this. Otherwise, as a user, I'd be quite let down if some of the configuration options aren't working and I only browsing the code will help. See e.g. https://docs.rs/tokio/latest/tokio/#feature-flags 

What do you think?

**Comment by hanabi1224** [comment]
That makes sense for crate doc. A application I assume current compress type options are for our own convenience to measure performance, imho it should eventually be some more user friendly option like --compression [yes|no], does that make sense?

**Comment by elmattic** [comment]
> That makes sense for crate doc. As for application I assume current compress type options are for our own convenience to measure performance, imho it should eventually be some more user friendly option like --compression [yes|no], does that make sense?


If we remove some compression libs, then we should remove some options here as well: https://github.com/ChainSafe/forest/blob/main/node/db/src/rocks_config.rs#L61

**Comment by hanabi1224** [comment]
@elmattic this should have been addressed by `#[cfg(feature = "...")]` lines, did I miss sth?

**Comment by hanabi1224** [comment]
@LesnyRumcajs 
Improved error message to list all available options:
```console
invalid compression option: lz44, valid options: bz2,lz4,lz4hc,snappy,zlib,none', node/db/src/rocks.rs:50:90
```

It's complicated to make them app level feature flags cuz we need to propagate those features all the way through the dependency chain, might not be worth it or we can do it in a separate PR.

**Review by LesnyRumcajs — APPROVED** [review]
It'd be nice to propagate those flags, otherwise, they're painful to utilise (i.e. one would need to edit manually some Cargo file IIUC). I'm okay with doing this in a separate PR or disregarding this comment if it doesn't make sense. :)

**Comment by elmattic** [comment]
> @elmattic this should have been addressed by `#[cfg(feature = "...")]` lines, did I miss sth?

Try to run forest like this:

Dump config first in `config.toml` and change compression with `compression_type = "zstd"`.

```
$ ./target/debug/forest --target-peer-count 50 --encrypt-keystore false -c config.toml 
2022-10-20T10:25:15.228Z INFO  forest::daemon > Starting Forest daemon, version 0.4.1+git.779293c1
2022-10-20T10:25:15.230Z INFO  forest_libp2p::service > Recovered libp2p keypair from "/Users/guillaume/Library/Application Support/com.ChainSafe.Forest/libp2p/keypair"
2022-10-20T10:25:15.230Z INFO  forest::daemon         > PeerId: 12D3KooWPvXJznug7GH2PHN7ov7YMhY3LDrphzR6SXdvZYEPJjPh
2022-10-20T10:25:15.232Z WARN  forest::daemon         > Warning: Keystore encryption disabled!
2022-10-20T10:25:15.233Z INFO  forest::daemon         > Prometheus server started at 127.0.0.1:6116
2022-10-20T10:25:15.234Z INFO  forest::daemon         > Admin token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.FfJKVLU-eF7DpIffgFixTmpPEC1XB68M-jmrTGC6qPM
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: invalid compression option: zstd, valid options: bz2,lz4,lz4hc,snappy,zlib,none', node/db/src/rocks.rs:50:90
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by elmattic** [comment]
> @LesnyRumcajs Improved error message to list all available options:
> 
> ```
> invalid compression option: lz44, valid options: bz2,lz4,lz4hc,snappy,zlib,none', node/db/src/rocks.rs:50:90
> ```
> 
> It's complicated to make them app level feature flags cuz we need to propagate those features all the way through the dependency chain, might not be worth it or we can do it in a separate PR.

Maybe also remove the `unwrap` and propate the error in `RocksDb::to_options` would be cleaner.

**Comment by hanabi1224** [comment]
@elmattic `zstd` is disabled by this PR because it builds slow, and the error message says
```console
invalid compression option: zstd, valid options: bz2,lz4,lz4hc,snappy,zlib,none'
```

I didn't get your suggestion abt `remove some options here as well`, could u plz elaborate?

**Comment by hanabi1224** [comment]
> It'd be nice to propagate those flags, otherwise, they're painful to utilise

@LesnyRumcajs It also adds non-trival maintainence burden to add those features, I think it will be better that we discuss and have a conclusion of whether we should expose these compression types to end users after we finish tweaking the db setup

**Comment by elmattic** [comment]
> @elmattic `zstd` is disabled by this PR because it builds slow, and the error message says
> 
> ```
> invalid compression option: zstd, valid options: bz2,lz4,lz4hc,snappy,zlib,none'
> ```
> 
> I didn't get your suggestion abt `remove some options here as well`, could u plz elaborate?

Sorry, didn't saw the commit 779293c14b9b02a9f5c4746ca777d1c198e72c89, so it's all good.

**Pull request merged**
