### PR TITLE
feat: make TipsetKey iterable

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

Changes introduced in this pull request:

- Implement `fn TipsetKey::iter`

## Reference issue to close (if applicable)

Closes https://github.com/ChainSafe/forest/issues/4024

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by LesnyRumcajs — COMMENTED** [review]
Would it make sense to implement the `Iterator` trait instead of a free method?

**Review by aatifsyed — APPROVED** [review]
I love it

**Comment by hanabi1224** [comment]
> Would it make sense to implement the `Iterator` trait instead of a free method?

@LesnyRumcajs I guess I can implement `IntoIterator` for `TipsetKey` and `&TipsetKey`

**Comment by LesnyRumcajs** [comment]
> > Would it make sense to implement the `Iterator` trait instead of a free method?
> 
> @LesnyRumcajs I guess I can implement `IntoIterator` for `TipsetKey` and `&TipsetKey`

Perhaps it's better to keep things simple. Up to you.

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by lemmih** [comment]
> > > Would it make sense to implement the `Iterator` trait instead of a free method?
> > 
> > 
> > @LesnyRumcajs I guess I can implement `IntoIterator` for `TipsetKey` and `&TipsetKey`
> 
> Perhaps it's better to keep things simple. Up to you.

I'd love to see it. `for p in block.parents` is prettier than `for p in block.parents.iter()`. :)

**Comment by hanabi1224** [comment]
> I'd love to see it. `for p in block.parents` is prettier than `for p in block.parents.iter()`. :)

@lemmih Will do

**Comment by hanabi1224** [comment]
> I'd love to see it. `for p in block.parents` is prettier than `for p in block.parents.iter()`. :)

@lemmih done.

**Pull request merged**
