### PR TITLE
Add optional jemalloc support

### LINKED ISSUE #2434: Test jemalloc allocator
**Issue summary**

We would like to test alternatives to the default system allocator used in Rust programs. jemalloc is one of those.

We are mainly interested in:
- Troubleshooting memory fragmentation (jemalloc has a reputation of creating much less fragmentation).
- Debugging features (ie heap profiling)

A first step would be to create a small code sample using jemalloc before trying on a bigger program like Forest.

**Other information and links**

https://github.com/tikv/jemallocator
https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:
- Add jemalloc support under a feature flag

A quick benchmark gives:

`./scripts/benchmark_db/bench.rb 2547360_2023_01_26T10_00_00Z.car --pattern 'paritydb*,baseline' --heights 60`

Bench | Import Time | Import RSS | DB Size
-|-|-|-
baseline | 7m 55s | 2.91GiB | 92.71GB
paritydb | 13m 11s | 4.11GiB | 122.02GB
paritydb+jemalloc | 12m 52s | 2.15GiB | 120.95GB
---
Bench | Validate Time | Validate RSS
-|-|-
baseline | 5m 52s | 3.69GiB
paritydb | 3m 45s | 4.00GiB
paritydb+jemalloc | 3m 55s | 3.01GiB

Running Forest and following the chain seems to require significantly less memory (more tests will come).

## Reference issue to close (if applicable)

Closes #2434

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is up-to-date. All user-facing changes should be reflected in this document.

### CODE REVIEW

**Review by hanabi1224 — APPROVED** [review]
Less memory! One more step towards having forest running on my old laptop for months

**Comment by elmattic** [comment]
> Less memory! One more step towards having forest running on my old laptop for months

How much memory do you have? I have 5 years old Core i3 and 16Gb and my Fedora is running fine.

**Comment by hanabi1224** [comment]
> How much memory do you have? I have 5 years old Core i3 and 16Gb and my Fedora is running fine.

@elmattic memory usage is no longer a problem, I was talking about disk space : )

**Comment by LesnyRumcajs** [comment]
image

With this feature enabled, it sits below 10G during mainnet snapshot export, whereas without it reaches ~20G. A *massive* improvement.

**Review by LesnyRumcajs — APPROVED** [review]
I want this. Could you please add it to the Makefile? You can re-use the target `install-with-partiydb`.

**Comment by elmattic** [comment]
> I want this. Could you please add it to the Makefile? You can re-use the target `install-with-partiydb`.

Done! Thanks for the suggestion.

**Pull request merged**
