### PR TITLE
Delete the test in peer_test.rs

### LINKED ISSUE #1861: Investigate the test in `peer_test.rs`
**Issue summary**

We have a module that contains a single test. This module is not used by the crate and the test is therefore not run. We should investigate what to do about this. Possible options:
- Use the module such that the test is run.
- Move the test to the `tests/` folder. This can only be done if the test doesn't depend on anything private from the crate.
- Remove the test. Maybe the test isn't relevant anymore and should be removed.

File in question: https://github.com/ChainSafe/forest/blob/main/blockchain/chain_sync/src/sync/peer_test.rs

**Other information and links**

### PR DESCRIPTION
**Pull request by tyshko5**
**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes #1861

**Other information and links**

### CODE REVIEW

**Comment by lemmih** [comment]
Please comment why you believe deleting the test is the best approach.

**Comment by lemmih** [comment]
And update the title of the PR accordingly.

**Comment by tyshko5** [comment]
> Please comment why you believe deleting the test is the best approach.

It was testing functions that don't exist anymore

**Comment by lemmih** [comment]
> > Please comment why you believe deleting the test is the best approach.
> 
> It was testing functions that don't exist anymore

Why don't they exist anymore?

**Comment by tyshko5** [comment]
> > > Please comment why you believe deleting the test is the best approach.
> > 
> > 
> > It was testing functions that don't exist anymore
> 
> Why don't they exist anymore?

It was removed during a refactor https://github.com/ChainSafe/forest/pull/1081

**Comment by LesnyRumcajs** [comment]
@tyshko5 what's the status of this PR?

**Comment by tyshko5** [comment]
> @tyshko5 what's the status of this PR?

I think we cannot rewrite this test, the code is too outdated, the structs used there don't exist and the ones, that replaces these ones have AFAI understand different behaviour. Moreover the tests checks the addition of full_peers, a thing that no longer exists after aforementioned refactor.

**Review by lemmih — APPROVED** [review]

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
> > @tyshko5 what's the status of this PR?
> 
> I think we cannot rewrite this test, the code is too outdated, the structs used there don't exist and the ones, that replaces these ones have AFAI understand different behaviour. Moreover the tests checks the addition of full_peers, a thing that no longer exists after aforementioned refactor.

Makes sense, thanks for investigating this further!

**Pull request merged**
