### PR TITLE
circleci: prepare build matrix

### PR DESCRIPTION
**Pull request by q9f**
- renamed `test-executor` to `linux-executor`
- updated `linux-executor` image to `ubuntu-2004:202107-02`
- renaned `mac-executor` to `macos-executor`
- updated `xcode` version to `13.0.0`
- renamed `install_rust` command to `install_rust_linux`
- added `install_rust_macos` command
- renamed `rust_setup` to `set_rustc_stable`
- added `set_rustc_nightly`
- added `linux-build-stable` job
- renamed `nightly-build-check` job to `linux-build-nightly`
- renamed `msrv-build-check` job to `linux-build-msrv`
- renamed `macos-build-check` job to `macos-build-stable`
- renamed `setup_test` to `test-checks`
- renamed `build-check` to `build-checks`
- renamed `daily-checks` to `nightly-checks`
- removed todos and unused stuff and stuff we shouldn't ignore

### CODE REVIEW

**Review by ec2 — COMMENTED** [review]
Not sure if we need the MacOS build tests 🤔

**Comment by q9f** [comment]
> Not sure if we need the MacOS build tests thinking

Yesterday you said, you don't know if it's building on macos.

I can also remove macos nightly and just keep stable. But one job on macos should be in place, don't you think?

**Review by ec2 — APPROVED** [review]
LGTM. Just remove MacOS nightly as discussed.

**Comment by q9f** [comment]
I removed mac nightly in 33c0603 and decided to restore msrv of 1.52.1 for now.

**Pull request merged**
