### PR TITLE
Fix cargo dependency missing feature for unit tests

### LINKED ISSUE #1776: Fix cargo dependency missing feature for unit tests
**Issue summary**

```sh
❯ cargo test --package key_management chain
error[E0599]: no method named `verify` found for struct `fvm_shared::crypto::signature::Signature` in the current scope
   --> key_management/src/wallet.rs:419:13
    |
419 |         sig.verify(&msg, &addr).unwrap();
    |             ^^^^^^ method not found in `fvm_shared::crypto::signature::Signature`

error[E0432]: unresolved import `async_std::stream::Interval`
 --> node/forest_libp2p/src/discovery.rs:4:31
  |
4 | use async_std::stream::{self, Interval};
  |  
```

**Other information and links**

### PR DESCRIPTION
**Pull request by jimluo**
**Summary of changes**
Changes introduced in this pull request:
- 
Add forest_libp2p and key_management packages  dependencies missing features for unit test.
@lemmih thanks  for your review,  I've just forked new repository and created new branch for PR.

**Reference issue to close (if applicable)**

Closes 
#1776

**Other information and links**

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@jimluo seems your second commit was done from another account, could you please make both from a single one?

**Review by LesnyRumcajs — CHANGES_REQUESTED** [review]
@jimluo Thanks for the contribution. If those features are required only for unit tests, they should be put under `[dev-dependencies]` section. Could you please try it out?

**Comment by lemmih** [comment]
Hi @jimluo. Are you still working on this PR?

**Comment by jimluo** [comment]
@LesnyRumcajs  @lemmih 
Sure, I will change it today.

**Pull request merged**
