### PR TITLE
chore: configure update groups for dependabot

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

Changes introduced in this pull request:

- Configure dependabot to update all patch versions with a single PR
- Configure dependabot to update `fil_actors*` crates with a single PR
- ~Bump versions of non-fvm crates~
- ~Bump all patch versions~

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by lemmih — APPROVED** [review]

**Review by lemmih — CHANGES_REQUESTED** [review]
Could you update `.github/dependabot.yml` and the dependencies in separate PRs?

**Comment by lemmih** [comment]
I would not have guessed this PR bumped dependencies based on its title.

**Comment by hanabi1224** [comment]
> Could you update `.github/dependabot.yml` and the dependencies in separate PRs?

@lemmih Done

**Review by LesnyRumcajs — APPROVED** [review]
Do we want a similar trick in the other repositories?

**Review by lemmih — APPROVED** [review]

**Comment by hanabi1224** [comment]
> Do we want a similar trick in the other repositories?

@LesnyRumcajs I can do that after verifying this change after it's merged

**Pull request merged**
