### PR TITLE
auto increase FD limit

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
## Summary of changes

Changes introduced in this pull request:

- this automatic soft FD limit increase should prevent issues like here [forest-mainnet_2023-08-09T19_50_17_forest.txt](https://github.com/ChainSafe/forest/files/12310960/forest-mainnet_2023-08-09T19_50_17_forest.txt)

```
2023-08-09T19:50:39.596081Z ERROR forest_filecoin::metrics::db: Calculating DB size for metrics failed: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" }), message: "Io error. Look inside err_kind for more details." }
2023-08-09T19:50:40.620353Z ERROR hyper::server::tcp: accept error: Too many open files (os error 24)
2023-08-09T19:50:41.621565Z ERROR hyper::server::tcp: accept error: Too many open files (os error 24)
2023-08-09T19:50:42.622454Z ERROR hyper::server::tcp: accept error: Too many open files (os error 24)
2023-08-09T19:50:43.624790Z ERROR hyper::server::tcp: accept error: Too many open files (os error 24)
```
Note that the value is a bit arbitrary, and we may need to increase it further.

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by lemmih — APPROVED** [review]

**Comment by elmattic** [comment]
@LesnyRumcajs What about the subcommands in `forest-tool`? Do we need to increase `fd`s here as well?

**Comment by lemmih** [comment]
> @LesnyRumcajs What about the subcommands in `forest-tool`? Do we need to increase `fd`'s here as well?

Those commands do not use ParityDB.

**Comment by LesnyRumcajs** [comment]
> @LesnyRumcajs What about the subcommands in `forest-tool`? Do we need to increase `fd`'s here as well?

Let's do it lazily - if any of `forest-cli` or `forest-tool` commands fail on low FD, we'll investigate whether it makes sense (might be a bug), and if it does, we'll increase it then. Does it sound good @elmattic ?

**Comment by elmattic** [comment]
> > @LesnyRumcajs What about the subcommands in `forest-tool`? Do we need to increase `fd`'s here as well?
> 
> Let's do it lazily - if any of `forest-cli` or `forest-tool` commands fail on low FD, we'll investigate whether it makes sense (might be a bug), and if it does, we'll increase it then. Does it sound good @elmattic ?

Sure.

**Review by ruseinov — APPROVED** [review]

**Review by creativcoder — APPROVED** [review]

**Pull request merged**
