### PR TITLE
added the check for config file via Env Var

### LINKED ISSUE #1191: `FOREST_CONFIG_PATH` env var
**Task summary**

In the interest of a better UX, if users often have specific config options they often like to override by default, such as having the store on a different disk or disabling `encrypt_keystore`, it might be nice to create an environment variable that points to a configuration file that can be overridden by explicitly providing an explicit config argument.

**Acceptance criteria**

- `FOREST_CONFIG_PATH` env var is read when checking for config file path in forest CLI (for both client and daemon)
- `-c, --config` argument overrides this setting

**Other information and links**

It's probably best the check should go here:
https://github.com/ChainSafe/forest/blob/32656db9a28120326a4fdb328cb751e1705de761/forest/src/cli/mod.rs#L130

### PR DESCRIPTION
**Pull request by leviathanbeak**
**Summary of changes**
Changes introduced in this pull request:
- improves UX by adding the check for config file via Env Var

**Reference issue to close (if applicable)**
Closes #1191 

**Other information and links**

### CODE REVIEW

**Comment by cryptoquick** [comment]
I'm very glad you decided to take this on! However, have you tested this? I'm not sure it works. This is what I get after running `make install`:

Screenshot from 2021-07-21 05-46-49

As you can see, it ignored my config setting to turn off keystore encryption. This occurs when running both as client and daemon.

Briefly looking at the code, I see no obvious reason why this doesn't work. If you can reproduce the issue, do you think you can figure out why the config file seems to be ignored, despite it being provided by the shell?

**Comment by cryptoquick** [comment]
Wait, I just realized, after checking out your repo, you have your changes in a branch. Recompiling now.

**Comment by cryptoquick** [comment]
It works perfectly! Good job!! Let's get this merged in, team, this is a substantial UX improvement (imo).

Screenshot from 2021-07-21 06-01-17

Screenshot from 2021-07-21 06-01-32

**Review by cryptoquick — APPROVED** [review]

**Review by ec2 — APPROVED** [review]

**Comment by leviathanbeak** [comment]
@cryptoquick @ec2 thanks for reviewing, I went outside after PR so wasn't able to respond, cheers

**Pull request merged**
