### PR TITLE
use paritydb by default

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
## Summary of changes

Changes introduced in this pull request:
- Switch to ParityDb as the default.

## Reference issue to close (if applicable)

Closes https://github.com/ChainSafe/forest/issues/2576

## Other information and links

If you were using the defaults, you must re-import the snapshot and delete the old rocksdb directory.

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is up-to-date. All user-facing changes should be reflected in this document.

### CODE REVIEW

**Review by hanabi1224 — APPROVED** [review]
Let's also ship either `jemalloc` or `mimalloc`!

**Comment by LesnyRumcajs** [comment]
> Let's also ship either `jemalloc` or `mimalloc`!

I'm unsure who won the `jemalloc` vs `mimalloc` battle? I'm okay with either. Thoughts?

**Comment by LesnyRumcajs** [comment]
Alternatively, we can do it in a separate PR once benchmarks are done.

**Review by lemmih — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
@hanabi1224 https://github.com/ChainSafe/forest/issues/2607

**Pull request merged**
