### PR TITLE
Add back wallet check test

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

This PR is adding back the check to the CI for trying to get more context about this Send FIL issue.

Changes introduced in this pull request:

- Add warning in case of unpublished messages
- Add `--show` flag to send command for printing the message
- Add back check of balance so we know when it happens
- Add 3 rounds of testing

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by lemmih** [comment]
Hmm, I'm not keen on using the CI for this kind of debugging. How about we do this testing on a droplet?

**Comment by elmattic** [comment]
> Hmm, I'm not keen on using the CI for this kind of debugging. How about we do this testing on a droplet?

I agree, it's not ideal. Let me propose something else. I can remove all the 3 rounds so it would not be more computation heavy than what we have today.
Once the check is failing again, then I will disable it so it doesn't get in the way (hopefully we will have more insights this time).
I've been looking at a dozen of Wallet tests lately and couldn't see the issue again.

**Comment by lemmih** [comment]
> > Hmm, I'm not keen on using the CI for this kind of debugging. How about we do this testing on a droplet?
> 
> I agree, it's not ideal. Let me propose something else. I can remove all the 3 rounds so it would not be more computation heavy than what we have today. Once the check is failing again, then I will disable it so it doesn't get in the way (hopefully we will have more insights this time). I've been looking at a dozen of Wallet tests lately and couldn't see the issue again.

Wouldn't it be just as good to run the `calibnet_wallet_check.sh` script in a loop on a droplet? We could set up 10 Forest nodes in parallel to run this script in a loop.

**Comment by elmattic** [comment]
> > > Hmm, I'm not keen on using the CI for this kind of debugging. How about we do this testing on a droplet?
> > 
> > 
> > I agree, it's not ideal. Let me propose something else. I can remove all the 3 rounds so it would not be more computation heavy than what we have today. Once the check is failing again, then I will disable it so it doesn't get in the way (hopefully we will have more insights this time). I've been looking at a dozen of Wallet tests lately and couldn't see the issue again.
> 
> Wouldn't it be just as good to run the `calibnet_wallet_check.sh` script in a loop on a droplet? We could set up 10 Forest nodes in parallel to run this script in a loop.

Yes, I can have a try, but I'm not sure if I will be able to reproduce exact same conditions that on the CI.

For example, the error Hubert managed to produce yesterday (https://github.com/ChainSafe/forest/issues/2726#issuecomment-1581147480) is not the same one we had on the CI. Because in his case there's an error but on our side we managed to print the message `CID` (meaning the message was successfully added to the pool).

**Comment by lemmih** [comment]
@elmattic Is the `--show` command something we want long-term? If not, let's close this PR and set up the testing separately on a droplet.

**Comment by elmattic** [comment]
> @elmattic Is the `--show` command something we want long-term? If not, let's close this PR and set up the testing separately on a droplet.

No. Once we have `mpool pending` we won't need it because we will be able to find it thanks to message CID (returned by send subcommand).

**Pull request closed without merging**
