### PR TITLE
fix: monitoring dashboard not showing any data

### PR DESCRIPTION
**Pull request by samuelarogbonlo**
## Summary of changes

Changes introduced in this pull request:

- monitoring dashboard not showing any data

## Reference issue to close (if applicable)

Closes https://github.com/ChainSafe/forest/issues/4593

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by ruseinov** [comment]
Has this been tested?

**Review by ruseinov — APPROVED** [review]
approved conditionally, please make sure to test this.

**Review by LesnyRumcajs — CHANGES_REQUESTED** [review]
It does not work on my machine.

image

**Comment by LesnyRumcajs** [comment]
@samuelarogbonlo any updates on this?

**Comment by samuelarogbonlo** [comment]
@LesnyRumcajs, sorry for the late reply. i tested this on fresh deployment and it worked fine, but i'll look into it.

**Comment by samuelarogbonlo** [comment]
@LesnyRumcajs, It’s working for me now with recent changes. Could you check again on your end?

Screenshot 2024-08-23 at 12 58 31 PM

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
