### PR TITLE
Revert "chore: upgrade libp2p to 0.52.1 (#3115)"

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
This reverts commit 4469ff43b02011244220c8a82dd4beafd3a0a437.

## Summary of changes

Changes introduced in this pull request:

- it seems the upgrade produced same issues as described in https://github.com/ChainSafe/forest/issues/2762

## Reference issue to close (if applicable)

Closes

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by aatifsyed** [comment]
Does this need a regression test?

**Comment by LesnyRumcajs** [comment]
> Does this need a regression test?

How would you achieve this? For context, it's not that the chain exchange failure happens all the time with the new version. It happens sometimes, even after 24 hours. Unfortunately, we do not know currently what exact conditions are triggering this (apart from the fact that it doesn't seem to happen with the older libp2p release)

**Comment by lemmih** [comment]
If we revert the PR, how will we debug the problem?

**Comment by LesnyRumcajs** [comment]
> If we revert the PR, how will we debug the problem?

We can debug it on a branch. It's essential not to restart our infrastructure services every time this issue appears.

**Review by lemmih — APPROVED** [review]

**Review by hanabi1224 — APPROVED** [review]

**Pull request merged**
