### PR TITLE
clippy::single_match_else pedantic check

### PR DESCRIPTION
**Pull request by tyshko5**
## Summary of changes

Changes introduced in this pull request:
- 

Needed for readability. `match` statements idiomatically should be used when there are at least 3 options for an enum. In case there clauses are long it's not obvious how many branches the code has. 

## Reference issue to close (if applicable)

Closes 

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is up-to-date. All user-facing changes should be reflected in this document.

### CODE REVIEW

**Comment by lemmih** [comment]
You need strong arguments for why `single_match_else` should be enabled. Add them to the PR description.

**Comment by LesnyRumcajs** [comment]
Personally, I don't find this more readable, but if others prefer it this way, I'm okay with the change.

**Comment by lemmih** [comment]
Your arguments:

1. Needed for readability.
2. `match` statements idiomatically should be used when there are at least 3 options for an enum.
3. In case there clauses are long it's not obvious how many branches the code has.

Counter-arguments:

1. I think matches are more readable than `if` statements.
2. I think this is just categorically incorrect. Matching on boolean values is better done with `if` but the same isn't true for other values with two options.
3. The indentation makes it obvious, no? In any case, I don't think chains of `if-else` are more obvious.

**Comment by lemmih** [comment]
> > Your arguments:
> > 
> > 1. Needed for readability.
> > 2. `match` statements idiomatically should be used when there are at least 3 options for an enum.
> > 3. In case there clauses are long it's not obvious how many branches the code has.
> > 
> > Counter-arguments:
> > 
> > 1. I think matches are more readable than `if` statements.
> > 2. I think this is just categorically incorrect. Matching on boolean values is better done with `if` but the same isn't true for other values with two options.
> > 3. The indentation makes it obvious, no? In any case, I don't think chains of `if-else` are more obvious.
> 
> My argument is not readability in general, but readability in case of `Option`s and `Result`s which is what is fixed in the PR. I'm not sure I understand your second argument fully. I am not a proponent of `if-else` chains.

Whether `if` is better than `match` for `Option`s is controversial and I don't feel your arguments are overwhelmingly persuasive. As such, I'm closing this PR.

The extra clippy hints listed in the parent issue are all disabled by default because they aren't appropriate in all projects. The work is not in updating our code-base, the work is in figuring out which hints are appropriate for Forest. If you don't strongly feel a lint is appropriate (and can argue for your convictions) then the lint should not be enabled.

**Comment by tyshko5** [comment]
> > > Your arguments:
> > > 
> > > 1. Needed for readability.
> > > 2. `match` statements idiomatically should be used when there are at least 3 options for an enum.
> > > 3. In case there clauses are long it's not obvious how many branches the code has.
> > > 
> > > Counter-arguments:
> > > 
> > > 1. I think matches are more readable than `if` statements.
> > > 2. I think this is just categorically incorrect. Matching on boolean values is better done with `if` but the same isn't true for other values with two options.
> > > 3. The indentation makes it obvious, no? In any case, I don't think chains of `if-else` are more obvious.
> > 
> > 
> > My argument is not readability in general, but readability in case of `Option`s and `Result`s which is what is fixed in the PR. I'm not sure I understand your second argument fully. I am not a proponent of `if-else` chains.
> 
> Whether `if` is better than `match` for `Option`s is controversial and I don't feel your arguments are overwhelmingly persuasive. As such, I'm closing this PR.
> 
> The extra clippy hints listed in the parent issue are all disabled by default because they aren't appropriate in all projects. The work is not in updating our code-base, the work is in figuring out which hints are appropriate for Forest. If you don't strongly feel a lint is appropriate (and can argue for your convictions) then the lint should not be enabled.

My argument was not that `if` is better than `match` in general, but only in specific circumstances this lint works. 

I indeed strongly feel this lint is not only appropriate, but should be mandatory for all Rust projects.

**Comment by lemmih** [comment]
> > > > Your arguments:
> > > > 
> > > > 1. Needed for readability.
> > > > 2. `match` statements idiomatically should be used when there are at least 3 options for an enum.
> > > > 3. In case there clauses are long it's not obvious how many branches the code has.
> > > > 
> > > > Counter-arguments:
> > > > 
> > > > 1. I think matches are more readable than `if` statements.
> > > > 2. I think this is just categorically incorrect. Matching on boolean values is better done with `if` but the same isn't true for other values with two options.
> > > > 3. The indentation makes it obvious, no? In any case, I don't think chains of `if-else` are more obvious.
> > > 
> > > 
> > > My argument is not readability in general, but readability in case of `Option`s and `Result`s which is what is fixed in the PR. I'm not sure I understand your second argument fully. I am not a proponent of `if-else` chains.
> > 
> > 
> > Whether `if` is better than `match` for `Option`s is controversial and I don't feel your arguments are overwhelmingly persuasive. As such, I'm closing this PR.
> > The extra clippy hints listed in the parent issue are all disabled by default because they aren't appropriate in all projects. The work is not in updating our code-base, the work is in figuring out which hints are appropriate for Forest. If you don't strongly feel a lint is appropriate (and can argue for your convictions) then the lint should not be enabled.
> 
> My argument was not that `if` is better than `match` in general, but only in specific circumstances this lint works.
> 
> I indeed strongly feel this lint is not only appropriate, but should be mandatory for all Rust projects.

Your objection is noted but my decision stands.

**Pull request closed without merging**
