### PR TITLE
Tidy up submit_windowed_post()

### PR DESCRIPTION
**Pull request by kirk-baird**
**Summary of changes**
Changes introduced in this pull request:
- Fixed outdated comments see this [PR](https://github.com/filecoin-project/specs-actors/pull/1410)
- Adjusted code to match Lotus more cleanly (there is no functional change just reads cleaner)

**Reference issue to close (if applicable)**

Closes n/a

**Other information and links**

### CODE REVIEW

**Review by ec2 — APPROVED** [review]

**Comment by kirk-baird** [comment]
Note: `cargo clippy` fails from files outside of what I touched I believe due to a new version of clippy adding extra conditions.  

I'm happy to fix it in this commit but don't want to overlap if it's being fixed in another commit.

**Comment by ec2** [comment]
@kirk-baird That's right, new clippy, new warnings 😵 
It was fixed in a recent commit https://github.com/ChainSafe/forest/pull/1098/commits/b4215f7c32971a37dabead4ef2beb1491d07ee6c
Just pull `main` into here and the Earth should start rotating again 😄

**Comment by kirk-baird** [comment]
> It was fixed in a recent commit [b4215f7](https://github.com/ChainSafe/forest/commit/b4215f7c32971a37dabead4ef2beb1491d07ee6c)
> Just pull `main` into here and the Earth should start rotating again

Looks like that commit hasn't been merged into `main` yet :( and I'm not sure which fork it is on.

**Review by creativcoder — APPROVED** [review]

**Review by olibearo — APPROVED** [review]
Thanks Kirk :+1:

**Pull request merged**
