### PR TITLE
CI: Include conformance tests in code coverage results

### PR DESCRIPTION
**Pull request by lemmih**
**Summary of changes**
Changes introduced in this pull request:
- Conformance tests weren't being included in the code coverage because the submodule containing all the test-vectors was not checked out. This PR pulls in the submodule before doing code coverage.

**Reference issue to close (if applicable)**

**Other information and links**

### CODE REVIEW

**Comment by lemmih** [comment]
Hmm, the conformance tests still aren't being run.

**Comment by lemmih** [comment]
Hmm, tarpaulin recompiles everything from scratch. I wonder how we can make it use the cache.

**Comment by LesnyRumcajs** [comment]
> Hmm, tarpaulin recompiles everything from scratch. I wonder how we can make it use the cache.

perhaps pass `--skip-clean` ? Not sure if it won't introduce any nasty side effects.

**Comment by lemmih** [comment]
> > Hmm, tarpaulin recompiles everything from scratch. I wonder how we can make it use the cache.
> 
> perhaps pass `--skip-clean` ? Not sure if it won't introduce any nasty side effects.

I'll give it a try.

**Comment by lemmih** [comment]
Coverage results in 29minuts isn't great but it might have to do for now. It's a shame tarpaulin doesn't run separate test binaries in parallel.

**Review by elmattic — APPROVED** [review]

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
rock-solid!

**Pull request merged**
