### PR TITLE
[automated] Update Lotus version in API tests

### PR DESCRIPTION
**Pull request by LeshyBot**
### Changes
- Updates Lotus version in the JSON-RPC API tests to the latest release.

### CODE REVIEW

**Review by hanabi1224 — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
The Lotus images were not uploaded for these tags. I'll ping Lotus team. https://hub.docker.com/r/filecoin/lotus-all-in-one/tags

**Comment by LesnyRumcajs** [comment]
Blocked by https://github.com/filecoin-project/lotus/issues/12188

**Comment by hanabi1224** [comment]
Let's queue #4480 together with this one.

**Comment by LesnyRumcajs** [comment]
@hanabi1224 Shall we cherry-pick [ddc1d3b](https://github.com/ChainSafe/forest/pull/4484/commits/ddc1d3bcec20a528dc8891eaf5dcec95052533d7) to your branch and close this PR?

**Comment by hanabi1224** [comment]
> Shall we cherry-pick [ddc1d3b](https://github.com/ChainSafe/forest/pull/4484/commits/ddc1d3bcec20a528dc8891eaf5dcec95052533d7) to your branch and close this PR?

@LesnyRumcajs Done.

**Pull request closed without merging**
